### ISSUE TITLE
[FEATURE] Adding the image of Drifty using characters, in the first line of the console

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#10]
**Describe the solution you'd like**
I want to add an image of Drifty (might be logo) printed using characters, for the first line of the console.

**Additional context**
Refer to [`this`](https://images.app.goo.gl/s2Df3KuydDnmtHSJ8) image. Here, the logo of the app is printed in the console. Similar thing needs to be done with Drifty. 
Contributors who want to take over this issue should at first comment below and then I will assign them with the task.

**Comment by itshypon** [comment]
I would like to work on this issue. Thanks !

**Comment by SaptarshiSarkar12** [comment]
Ok @itshypon , assigning you with the task. Please link this issue to your PR.

**Comment by thexahmed00** [comment]
I would like to take this issue can you assign me, please? this will be my first pull request I'll be grateful :)

**Comment by SaptarshiSarkar12** [comment]
> I would like to take this issue can you assign me, please? this will be my first pull request I'll be grateful :)

Sorry, the work has been competed by the contributor. So, after the PR for this issue is approved, i shall review your PR (#12 ).

**Comment by thexahmed00** [comment]
Have a look I have created an Ascii Art
![image](https://user-images.githubusercontent.com/58472920/193269146-4ebcc367-dc82-466b-94d1-8e7d3860b010.png)

**Comment by SaptarshiSarkar12** [comment]
Ok @thexahmed00, yes it's a nice one.

**Comment by SaptarshiSarkar12** [comment]
@thexahmed00 you can still modify the banner that @itshypon will add through his PR, using another PR. Then, let me see which one is nice.

**Comment by thexahmed00** [comment]
what modification has to be done @SaptarshiSarkar12 pls let me know

**Comment by SaptarshiSarkar12** [comment]
@thexahmed00
Once @itshypon 's PR gets merged, if you think that the banner needs some change,  you can open a PR to include those changes.

**Comment by thexahmed00** [comment]
ok

**Comment by SaptarshiSarkar12** [comment]
@thexahmed00 please open an issue at first and then link that issue with your PR. This helps me to properly track the progress of Drifty.

**Comment by SaptarshiSarkar12** [comment]
@thexahmed00 If you want to modify the CLI banner, you may do so through another issue linked to your PR. I am closing this now.
