### ISSUE TITLE
designing

### ISSUE THREAD

**Issue by divyanshiet** [SaptarshiSarkar12/Drifty#100]
### Description

contact us part and part below it should be merged under another heading since some part are common among them, it made your site less complex and beautiful

### Application Version

v1.1.0

**Comment by SaptarshiSarkar12** [comment]
Great @divyanshiet! Do you want to work on this issue?

**Comment by divyanshiet** [comment]
ya sure @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
> ya sure @SaptarshiSarkar12

Ok assigning you with the task. Please link this issue with your PR.

**Comment by divyanshiet** [comment]
ok

**Comment by divyanshiet** [comment]
check your mail @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
> check your mail @SaptarshiSarkar12

Checked

**Comment by divyanshiet** [comment]
updated index.html and style.css do check

**Comment by SaptarshiSarkar12** [comment]
@divyanshiet Please open a Pull Request.
