### ISSUE TITLE
[BUG] Non functioning About button

### ISSUE THREAD

**Issue by i-ujjwaljha** [SaptarshiSarkar12/Drifty#101]
### Describe the bug

When we click the 'About' button, we aren't getting any response. I would like to fix that bug and if required I can also add an about section to it.

### Steps To Reproduce

1. Go to the 'About' button.
2. Click on it.
3. The button is getting clicked but isn't directing the user anywhere.

### Operating System

Windows

### Application Version

v1.1.0

**Comment by SaptarshiSarkar12** [comment]
Yes @i-ujjwaljha, you can add about section, that will be better. Assigning you with the task. Please link this issue to your PR.

**Comment by i-ujjwaljha** [comment]
Thank you. Working on it.

**Comment by SaptarshiSarkar12** [comment]
> Thank you. Working on it.

@i-ujjwaljha Welcome, please pull the latest changes before you start working on it.

**Comment by SaptarshiSarkar12** [comment]
> @i-ujjwaljha How much work has been done ?

@i-ujjwaljha Please respond else I would review #128 .

**Comment by SaptarshiSarkar12** [comment]
> > @i-ujjwaljha How much work has been done ?
> 
> @i-ujjwaljha Please respond else I would review #128 .

As @i-ujjwaljha is not responding, i am going to review #128 and shall close this issue.
