### ISSUE TITLE
Change the "Download Here" text design.

### ISSUE THREAD

**Issue by AshwinSatyawan** [SaptarshiSarkar12/Drifty#102]
### Description

![image](https://user-images.githubusercontent.com/40487239/194827832-a917c2f2-41ab-4e89-8cd3-8119b7ccd58e.png)
download button looks weird design-wise

### Application Version

v1.1.0

**Comment by AshwinSatyawan** [comment]
assign to me i have resolved

**Comment by SaptarshiSarkar12** [comment]
ok @AshwinSatyawan .

**Comment by SaptarshiSarkar12** [comment]
Please link this issue to your PR. @AshwinSatyawan
