### ISSUE TITLE
[BUG]  The Home page para is overlapping to the logo

### ISSUE THREAD

**Issue by saran1522** [SaptarshiSarkar12/Drifty#107]
### Describe the bug

The home page para is overlapping with the logo. 

### Steps To Reproduce

Heading and para need to go a little downwards.

### Operating System

Windows

### Application Version

v1.1.0

### Screenshots

<img width="298" alt="Screenshot 2022-10-10 180901" src="https://user-images.githubusercontent.com/90507409/194869497-97562871-f201-4e8e-9a5b-c1f035ffea38.png">

**Comment by saran1522** [comment]
please assign this issue to me under hacktoberfest

**Comment by prachisharma02** [comment]
please assign to me for hacktoberfest

**Comment by SaptarshiSarkar12** [comment]
As @saran1522 commented before @prachisharma02, I shall assign @saran1522 .

@prachisharma02 You can modify it after @saran1522's PR is merged. Or, you may work on other part of the project.

**Comment by saran1522** [comment]
@SaptarshiSarkar12 Thank you!
