### ISSUE TITLE
[BUG] Failed to create the directory in default download folder

### ISSUE THREAD

**Issue by itshypon** [SaptarshiSarkar12/Drifty#11]
**Describe the bug**
When the application asks us to download file in default downloads folder and we type 'Y'. It generates error as : 'Failed to create the directory'

**To Reproduce**
1. Download the application at Desktop and open it.
2. Enter the link to the file, take any image from google.
3. Press Y when asking for default downloads folder.
4. A message will pop up as : Default download folder detected and then an error will pop up as : Failed to create the directory.

**Expected behavior**
It should have downloaded the file in default download folder of windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/30335924/193183964-53d8459e-2fbb-4aa6-b834-60dc35df4bf8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

**Comment by SaptarshiSarkar12** [comment]
If anyone wants to resolve this bug, should comment here and I will assign them with the task.

**Comment by FireNdIce3** [comment]
Hi there! Can I work on this issue?

**Comment by SaptarshiSarkar12** [comment]
Yes @FireNdIce3 . Please link this issue to your PR.

**Comment by SaptarshiSarkar12** [comment]
@FireNdIce3 how far is the work done?

**Comment by aryan-upa** [comment]
Hey, I've solved the issue, can you assign this to me.

**Comment by SaptarshiSarkar12** [comment]
Let me first get some updates from @FireNdIce3 . If @FireNdIce3 does not respond, then , i shall assign you. 
@aryan-upa You may open the PR, i shall review it.

**Comment by SaptarshiSarkar12** [comment]
@FireNdIce3 Please respond
