### ISSUE TITLE
[BUG] Automatic detection of downloads folder broken for unix based operating systems

### ISSUE THREAD

**Issue by poshi1865** [SaptarshiSarkar12/Drifty#111]
### Describe the bug

Automatic detection of downloads folder is broken for operating systems where `/` is used as a file separator. 

### Steps To Reproduce

1. Start drifty
2. Enter a url
3. When you are asked if you want to download the file in your default downloads folder, press Y.
4. If you are on an os where the directory structure uses the `/` character as a separator, Drifty breaks.

### Operating System

Linux

### Application Version

v1.1.0

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 Yeah I can work on this, please assign me.

**Comment by singloon** [comment]
Should the downloads folder be already created?

**Comment by SaptarshiSarkar12** [comment]
> Should the downloads folder be already created?

@poshi1865

**Comment by SaptarshiSarkar12** [comment]
> Should the downloads folder be already created?

Yes, it needs to be. Dirfty only detects it and if it fails in it, it asks to enter a directory where the file needs to be downloaded.

**Comment by poshi1865** [comment]
> Should the downloads folder be already created?

There is no necessity because even if it is not present, Drifty will ask for a new location. However, when a new location is entered, Drifty **always** converts it to a windows-like path format (with `\` ). This behaviour is incorrect.
