### ISSUE TITLE
[FEATURE] The ability to download earlier releases 

### ISSUE THREAD

**Issue by redet-G** [SaptarshiSarkar12/Drifty#113]
### Is your feature request related to a problem? Please describe.

The website currently is only linked to the most recent release. Earlier releases could also be added.

### Describe the solution you'd like.

We could send a request to GitHub to list out release data. we could dynamically render the list of alternative download on the website.

### Application Version

v1.1.0

**Comment by SaptarshiSarkar12** [comment]
Great @redet-G ! Do you want to work on this issue?

**Comment by redet-G** [comment]
Yes!

**Comment by SaptarshiSarkar12** [comment]
Ok. Please link this issue to your Pull request and leave a star if you liked this project. @redet-G
