### ISSUE TITLE
[DOCS] Readme has to be updated to let users/contributors know about yt-dlp 

### ISSUE THREAD

**Issue by poshi1865** [SaptarshiSarkar12/Drifty#114]
### How would you improve the documentation? Please describe.

Adding documentation to help user/contributors figure out how to download yt-dlp and run Drifty smoothly.

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 you can assign this to me.

**Comment by poshi1865** [comment]
By the way, while testing #110 did you download yt-dlp and put it in the same directory as the Drifty exe, or did you add it to your path?

**Comment by SaptarshiSarkar12** [comment]
No, I haven't added it to my path. It was just in the directory where Drifty was run.

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 you can assign this to me.

Ok @poshi1865 , assigning you.

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 Should I also add the link for yt-dlp to the website?

**Comment by SaptarshiSarkar12** [comment]
@poshi1865 The user will not need to download yt-dlp manually as I have added that exe file as a part of the jar file as well as the cli exe file and runs quite well.

**Comment by SaptarshiSarkar12** [comment]
Closing this issue by that.
