### ISSUE TITLE
[FEATURE] Drifty should show the progress bar while downloading youtube videos, and not output from yt-dlp.

### ISSUE THREAD

**Issue by poshi1865** [SaptarshiSarkar12/Drifty#115]
### Describe the solution you'd like.

Currently Drifty shows the output from yt-dlp while downloading youtube videos. Instead, the progress bar from the ProgressBarThread class should be shown. 

### Application Version

v1.1.0

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 I am a little busy right now, will let you know if I can

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 I am a little busy right now, will let you know if I can

ok @poshi1865

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 I am a little busy right now, will let you know if I can

Can you work on this issue @poshi1865 ?

**Comment by SaptarshiSarkar12** [comment]
@poshi1865 I have successfully fixed this issue by passing `-q` command to `yt-dlp`. It now prints only the progress bar. 
### **There's one problem that errors from `yt-dlp` about the file are not printed.** If anyone wish to solve that, please open an issue for that.

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 Okay great!

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 Okay great!

Can you solve the problem that I have just mentioned?  @poshi1865

**Comment by poshi1865** [comment]
Yeah I can, is there an open issue related to that? Or should I create one?

**Comment by SaptarshiSarkar12** [comment]
> Yeah I can, is there an open issue related to that? Or should I create one?

@poshi1865 you need to create an issue for that. Also please comment your name there and i would assign you with the task.

**Comment by poshi1865** [comment]
Okay, could you please describe it in detail?

**Comment by SaptarshiSarkar12** [comment]
> Okay, could you please describe it in detail?

@poshi1865 The errors that `yt-dlp` prints in it's console are not printed by Drifty. One such error that I have encountered is downloading a private YouTube video. `yt-dlp` shows this error - 
```
ERROR: [youtube] JGXK_99nc5s: Private video. Sign in if you've been granted access to this video
```
But Drifty doesn't print it.
