### ISSUE TITLE
[FEATURE] Download button should download both Drifty and yt-dlp

### ISSUE THREAD

**Issue by poshi1865** [SaptarshiSarkar12/Drifty#118]
### Describe the solution you'd like.

Both the download buttons on the website should download yt-dlp along with Drifty. This will be a temporary change to help users/contributors run Drifty until an installation package is added. 

### Application Version

v1.1.0

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 you can assign me. I wanted to separate the readme from this issue because that had the documentation label.

**Comment by SaptarshiSarkar12** [comment]
ok @poshi1865 .

**Comment by SaptarshiSarkar12** [comment]
@poshi1865 The user will not need to download yt-dlp manually as I have added that exe file as a part of the jar file as well as the cli exe file and runs quite well. Closing this issue by that.
