### ISSUE TITLE
[BUG]  Drifty does not show progress bar and errors encountered while downloading youtube videos.

### ISSUE THREAD

**Issue by poshi1865** [SaptarshiSarkar12/Drifty#125]
### Describe the bug

 The errors that yt-dlp prints in it's console are not printed by Drifty. For example, while downloading a private YouTube video, yt-dlp shows this error: 
`ERROR: [youtube] JGXK_99nc5s: Private video. Sign in if you've been granted access to this video`

Drifty does not show this.

### Steps To Reproduce

1. Run Drifty
2. Paste the link for a private youtube video and try to download
3. No error message shown.

### Expected Behavior

Expected output is an error message

### Operating System

Linux

### Application Version

v1.2.0

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 Could I please be assigned to this?

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 Could I please be assigned to this?

Yes @poshi1865 . Please link this issue to your PR.

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 I noticed that the progress bar does not show when ytdlp downloads a video. I only see `Downloading....`

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 I noticed that the progress bar does not show when ytdlp downloads a video. I only see `Downloading....` Is this intentional, or a bug?

@poshi1865 Please attach a screenshot along with the inputs you have provided which has led to the error.

**Comment by poshi1865** [comment]
![Drifty bug](https://user-images.githubusercontent.com/63964405/196734631-33196fe8-0fbe-4ee6-a442-80cd069efe9a.jpeg)

**Comment by poshi1865** [comment]
> ![Drifty bug](https://user-images.githubusercontent.com/63964405/196734631-33196fe8-0fbe-4ee6-a442-80cd069efe9a.jpeg)

@SaptarshiSarkar12 This is what I was talking about

**Comment by SaptarshiSarkar12** [comment]
> > ![Drifty bug](https://user-images.githubusercontent.com/63964405/196734631-33196fe8-0fbe-4ee6-a442-80cd069efe9a.jpeg)
> 
> @SaptarshiSarkar12 This is what I was talking about

@poshi1865 Yes, then it's surely a bug. Please open an issue and you _may_ comment there if you want to work on that. 
Thanks for reporting !

**Comment by SaptarshiSarkar12** [comment]
> > > ![Drifty bug](https://user-images.githubusercontent.com/63964405/196734631-33196fe8-0fbe-4ee6-a442-80cd069efe9a.jpeg)
> > 
> > 
> > @SaptarshiSarkar12 This is what I was talking about
> 
> @poshi1865 Yes, then it's surely a bug. Please open an issue and you _may_ comment there if you want to work on that. Thanks for reporting !

Or you may make those changes through the same PR linked to this issue, just modify the description of this issue accordingly.

**Comment by poshi1865** [comment]
> > > > ![Drifty bug](https://user-images.githubusercontent.com/63964405/196734631-33196fe8-0fbe-4ee6-a442-80cd069efe9a.jpeg)
> > > 
> > > 
> > > @SaptarshiSarkar12 This is what I was talking about
> > 
> > 
> > @poshi1865 Yes, then it's surely a bug. Please open an issue and you _may_ comment there if you want to work on that. Thanks for reporting !
> 
> Or you may make those changes through the same PR linked to this issue, just modify the description of this issue accordingly.

Yeah I just did this, will make a pr soon.

**Comment by SaptarshiSarkar12** [comment]
> > > > > ![Drifty bug](https://user-images.githubusercontent.com/63964405/196734631-33196fe8-0fbe-4ee6-a442-80cd069efe9a.jpeg)
> > > > 
> > > > 
> > > > @SaptarshiSarkar12 This is what I was talking about
> > > 
> > > 
> > > @poshi1865 Yes, then it's surely a bug. Please open an issue and you _may_ comment there if you want to work on that. Thanks for reporting !
> > 
> > 
> > Or you may make those changes through the same PR linked to this issue, just modify the description of this issue accordingly.
> 
> Yeah I just did this, will make a pr soon.

**Comment by SaptarshiSarkar12** [comment]
Great @poshi1865!

**Comment by poshi1865** [comment]
https://user-images.githubusercontent.com/63964405/197023479-68e6ccfb-008a-4f5b-96be-23f2a235beea.mp4

@SaptarshiSarkar12 does this look Ok?

**Comment by SaptarshiSarkar12** [comment]
> drifty_fix.mp4 
> @SaptarshiSarkar12 does this look Ok?

@poshi1865 Please send the jar. I need to check it once after converting it into exe file.

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 I have mailed you a gdrive link to the jar file

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 I have mailed you a gdrive link to the jar file

ok @poshi1865 shall check it and let you know if it works.

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 Hi! Any update?

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 Hi! Any update?

Not checked due to repair of my laptop. @poshi1865

**Comment by SaptarshiSarkar12** [comment]
Shall inform you @poshi1865 😄

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 Hi! Any update?

Yes @poshi1865 it works successfully on my pc. You may open a PR.

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 Done! Please review and let me know. Thanks!

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 Done! Please review and let me know. Thanks!

Reviewed #143 @poshi1865 ! 👍
