### ISSUE TITLE
[BUG] Clicking on About does nothing.

### ISSUE THREAD

**Issue by Kamlesh72** [SaptarshiSarkar12/Drifty#127]
### Describe the bug

When we click on Home, Contribute, Download etc.. it goes to specific section. But when we click on About, nothing happens.
It should take us to About section.

### Steps To Reproduce

1. Go to Home page
2. Click About

### Expected Behavior

It should take us on "More Information About Drifty"

### Operating System

MacOS

### Application Version

v1.2.0

**Comment by Kamlesh72** [comment]
Pull request #128

**Comment by SaptarshiSarkar12** [comment]
@Kamlesh72 As you have opened a duplicate issue of #101, you need to wait for @i-ujjwaljha to respond. If @i-ujjwaljha does not respond within a few days (~2 -3 days maximum), I shall review your PR (#128).

**Comment by Kamlesh72** [comment]
Ya sure. Actually I didn't know about that, So I made a duplicate PR.
Well if he doesn't respond I would also like to add an About Section with more Info.

**Comment by Luciferr-18** [comment]
assign it to me

**Comment by SaptarshiSarkar12** [comment]
> assign it to me

Ya sure @Luciferr-18 .

**Comment by SaptarshiSarkar12** [comment]
As @sharvit18 no longer wants to work on it as he is busy, so, I am unassigning @sharvit18. If anyone wishes to work on it, he/she may comment below.

**Comment by anantnipunge** [comment]
I'm availabel to work on it please assign me this issue @SaptarshiSarkar12 . Please add hacktoberfest label.

**Comment by anantnipunge** [comment]
Also please tell me exactly what should i add in about section

**Comment by SaptarshiSarkar12** [comment]
> Also please tell me exactly what should i add in about section @SaptarshiSarkar12

The about page will contain my GitHub readme along with my avatar.
@anantnipunge

**Comment by anantnipunge** [comment]
Ya okay working on it. I will submit it soon

**Comment by anantnipunge** [comment]
Okay will submit it soon.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anantnipunge** [comment]
Hello @SaptarshiSarkar12 should i create new div for about page. Or should i only redirect to the readme.md on click `about`

**Comment by SaptarshiSarkar12** [comment]
> Hello @SaptarshiSarkar12 should i create new div for about page. Or should i only redirect to the readme.md on click `about`

Yes, create a new div. But, **how about creating separate pages for each nav elements (including the about section)? This may decrease load time of the website.** You may do so using another issue.

**Comment by anantnipunge** [comment]
Okay let me do once. Then you can review it. If it looks good then i will push the code. Otherwise, will work on same section by using another way.

Okay??

**Comment by SaptarshiSarkar12** [comment]
> Okay let me do once. Then you can review it. If it looks good then i will push the code. Otherwise, will work on same section by using another way.
> 
> Okay?? @SaptarshiSarkar12

ok @anantnipunge

**Comment by anantnipunge** [comment]
i have created the `About` section please check PR #167 @SaptarshiSarkar12 .

**Comment by anantnipunge** [comment]
i have created new issue #169 please assign me this issue. @SaptarshiSarkar12
