### ISSUE TITLE
[FEATURE] Allow inputting the requested parameters as program arguments

### ISSUE THREAD

**Issue by ChiefArug** [SaptarshiSarkar12/Drifty#13]
**Is your feature request related to a problem? Please describe.**
Currently you have to manually put in each argument as the program asks for them, this would allow inputting some or all of them as program arguments.

**Describe the solution you'd like**
Allow passing the various inputs it asks for as program arguments. They should be input in the same order as asked for, so `link fName downloadsFolder`. The program should still ask for any values not provided, or if a blank value was provided.
if downloadsFolder is `y` then it should try to find the default downloads folder. If it cannot find that or `n` was passed in then it should ask for one. If it is any other value it should be interpreted as a path. This may cause a conflict with saving to drives named `y` or `n`, I am not sure how that works exactly. If that is a problem then this could be split into two arguments, one for if a custom path should be used and a second for the custom path.

It could be worthwhile reording the arguments so that `link` and `fName` come last, which would make it easier to have a sort of 'default' downloader setup that has the downloads folder selected.

Example program arguments: `https://example.com/my_file.txt "My file.txt" y` which would download the file from the mentioned link and save it as `My file.txt` in the default downloads folder if found, asking the user for input if it cannot be found.

**Comment by Rishav-12** [comment]
hey @SaptarshiSarkar12 can I take this up? Let me know

**Comment by SaptarshiSarkar12** [comment]
Yes @Rishav-12 . Please make sure that you will link this issue to your PR.

**Comment by Rishav-12** [comment]
Hey, I'm sorry but I think I won't be able to do this since my code breaks for some reason and I'm not willing to dive too much into these errors. So I'll unassign myself, if anyone else wants to take this up feel free

**Comment by SaptarshiSarkar12** [comment]
Ok @Rishav-12 .
If anyone wants to work on this issue, please comment below and I shall assign you with the task.

**Comment by Anurag-Bharati** [comment]
I can work on this.

**Comment by SaptarshiSarkar12** [comment]
> I can work on this.

Okay, assigning you with the task. Please link this issue to your PR
