### ISSUE TITLE
[FEATURE] Enhancing the styling of social media icons in the footer.

### ISSUE THREAD

**Issue by codedmachine111** [SaptarshiSarkar12/Drifty#136]
Hello @SaptarshiSarkar12 . I would love to contribute by adding a better styling of fill-in appropriate color effect to the social media icons in the footer. Kindly assign me this issue.

### Description

I would love to contribute by adding a decent, yet attractive styling with hover effects to the social media icons in the footer.

### Application Version

v1.2.0

**Comment by SaptarshiSarkar12** [comment]
ok @codedmachine111 , assigning you with the task.
