### ISSUE TITLE
[FEATURE] Loading release note on demand on download section

### ISSUE THREAD

**Issue by redet-G** [SaptarshiSarkar12/Drifty#141]
### Describe the solution you'd like.

Adding more information like the release note, download count and file size on demand perhaps when clicking on `More` link. The release note is in markdown we need to convert it to html. 

### Application Version

v1.2.0

**Comment by SaptarshiSarkar12** [comment]
@redet-G Do you want to work on this issue?

**Comment by redet-G** [comment]
Sure

**Comment by SaptarshiSarkar12** [comment]
> Sure

Great @redet-G
