### ISSUE TITLE
[FEATURE] Multithreaded downloading for faster download speed

### ISSUE THREAD

**Issue by redet-G** [SaptarshiSarkar12/Drifty#145]
### Is your feature request related to a problem? Please describe.

When downloading larger files it is usually great to download the file in multiple channels similar to IDM.

### Describe the solution you'd like.

Upon detecting the file size, confirm that it is above a certain threshold. If the condition is met, it should start multiple downloader threads to download parts of the files. Once all the threads have finished downloading, the whole file is constructed from the parts.

### Application Version

v1.2.1

**Comment by SaptarshiSarkar12** [comment]
Great @redet-G, do you want to work on this issue?

**Comment by SaptarshiSarkar12** [comment]
### If anyone else wants to work on this issue, please comment below and I shall assign you with the task.

**Comment by SaptarshiSarkar12** [comment]
> Great @redet-G, do you want to work on this issue?

@redet-G Do you want to work on this issue? Please respond.

**Comment by redet-G** [comment]
alright you can assign this to me

**Comment by SaptarshiSarkar12** [comment]
> alright you can assign this to me

Ok @redet-G
