### ISSUE TITLE
Text Animations and Footer Design[FEATURE] 

### ISSUE THREAD

**Issue by khushigarg1** [SaptarshiSarkar12/Drifty#146]
### Is your feature request related to a problem? Please describe.

There is no text animations and there is no design in footer also. 

### Describe the solution you'd like.

I would like to add some text animations and footer with wavy effect. Can you assign this issue to me?

### Application Version

v1.2.0

### Screenshots

NA

### Additional information

NA

**Comment by SaptarshiSarkar12** [comment]
Yes, you can work on this @khushigarg1 .

**Comment by khushigarg1** [comment]
Thank You!
