### ISSUE TITLE
[FEATURE] URL checks are required

### ISSUE THREAD

**Issue by thexahmed00** [SaptarshiSarkar12/Drifty#15]
### Check for user input
whenever the user inputs a **link** drifty should check if it is in proper URL format or not
for eg.
_Enter the link to the file: fs_ 
**prompt: enter a valid URL**

**Comment by SaptarshiSarkar12** [comment]
@thexahmed00 thanks for this issue. It's a great issue.
If anyone wants to work on this issue, please commemt below. I would assign you with the task.

**Comment by SaptarshiSarkar12** [comment]
Ok @akshatjainei . Assigning you. Please make sure that you will link this issue to your PR.
