### ISSUE TITLE
[FEATURE] Add more Feature to home page at footer

### ISSUE THREAD

**Issue by anantnipunge** [SaptarshiSarkar12/Drifty#155]
### Is your feature request related to a problem? Please describe.

footer looks incomplete without the following feature.
1 . privacy policy
2 . t & c
3 . career
4 . contact us
5 . partner
6 . community
7 . opportunity

### Describe the solution you'd like.

i think there should have:
1 . privacy policy
2 . t & c
3 . career
4 . contact us
5 . partner
6 . community
7 . opportunity

it will look more concise.

### Application Version

v1.2.2

**Comment by anantnipunge** [comment]
please assign me this issue and add hacktoberfest label on completion.

**Comment by SaptarshiSarkar12** [comment]
> please assign me this issue and add hacktoberfest label on completion.

Ya sure @anantnipunge .

**Comment by anantnipunge** [comment]
thank you working on it. i will submit it soon.

**Comment by SaptarshiSarkar12** [comment]
> thank you working on it. i will submit it soon.

Welcome ❤️ ! 
Waiting for your PR...
