### ISSUE TITLE
[BUG] Yes/No input prompts should not exit with an error upon no input

### ISSUE THREAD

**Issue by redet-G** [SaptarshiSarkar12/Drifty#158]
### Describe the bug

If the use did not respond with Yes/No option and press enter it exits with an exception error.

### Steps To Reproduce

1. Insert a link to download a file
2. When it requests you to rename the just press `enter` key
```
  Filename detected : Adobe_After_Effects_2023_v23.0.0.59.rar
  Would you like to rename this file? (Enter Y for yes and N for no) : 
  Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	  at java.lang.String.charAt(String.java:658)
	  at Drifty_CLI.main(Drifty_CLI.java:95)
````

### Expected Behavior

The correct behavior would be to set a default response and an enter key would assume the default response.

### Operating System

Windows

### Application Version

v1.2.2

### Screenshots

```
Filename detected : Adobe_After_Effects_2023_v23.0.0.59.rar
Would you like to rename this file? (Enter Y for yes and N for no) : 
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at Drifty_CLI.main(Drifty_CLI.java:95)
````

**Comment by SaptarshiSarkar12** [comment]
Thanks for reporting @redet-G !
Do you want to work on this issue ? @redet-G

**Comment by SaptarshiSarkar12** [comment]
ok as @redet-G is not responding I can work on this issue.

**Comment by SaptarshiSarkar12** [comment]
> Thanks for reporting @redet-G ! Do you want to work on this issue ? @redet-G

Please respond @redet-G else I may work on this issue.

**Comment by redet-G** [comment]
You can work on this @SaptarshiSarkar12. Thank you for waiting me to response.

**Comment by SaptarshiSarkar12** [comment]
> You can work on this @SaptarshiSarkar12. Thank you for waiting me to response.

ok @redet-G

**Comment by SaptarshiSarkar12** [comment]
Closing this as it has been fixed by me through https://github.com/SaptarshiSarkar12/Drifty/commit/9baddbdf7e7de344b0d4244fc3d59424f9eebd20 .
