### ISSUE TITLE
Dockerize Website

### ISSUE THREAD

**Issue by naXa777** [SaptarshiSarkar12/Drifty#159]
### Description

I propose to containerize your static HTML website. Add Dockerfile and docker-compose.yml to your project's Website module.
More information in the article -> https://tecadmin.net/tutorial/docker-run-static-website
I'm going to follow it step by step. Please assign me to this task.

Read here to learn more about what is Docker and why it's used https://www.docker.com/why-docker/

### Application Version

v1.2.2

### Additional information

Do you have a preferred webserver: Nginx or Apache?

**Comment by SaptarshiSarkar12** [comment]
> ### Description
> I propose to containerize your static HTML website. Add Dockerfile and docker-compose.yml to your project's Website module. More information in the article -> https://tecadmin.net/tutorial/docker-run-static-website I'm going to follow it step by step. Please assign me to this task.
> 
> Read here to learn more about what is Docker and why it's used https://www.docker.com/why-docker/
> 
> ### Application Version
> v1.2.2
> 
> ### Additional information
> Do you have a preferred webserver: Nginx or Apache?

Yes you can @naXa777 .
Any web server you can use.

**Comment by SaptarshiSarkar12** [comment]
@naXa777 How much is the work done?

**Comment by naXa777** [comment]
Sorry. The progress is at 0% currently. I'm going to get back to this later.

**Comment by SaptarshiSarkar12** [comment]
> Sorry. The progress is at 0% currently. I'm going to get back to this later.

Ok you my start working on it when you are free. @naXa777

**Comment by naXa777** [comment]
in progress...

**Comment by naXa777** [comment]
see PR #189

**Comment by SaptarshiSarkar12** [comment]
> see PR #189

Shall review it @naXa777 soon. Actually, my computer is under repair, so, shall be reviewing after that.

**Comment by naXa777** [comment]
I'm cool with that. Hacktoberfest is over, no hurry :D

**Comment by SaptarshiSarkar12** [comment]
> I'm cool with that. Hacktoberfest is over, no hurry :D

Ok @naXa777 , meanwhile you may join our discord Server for the project's Discussions - https://discord.com/invite/DeT4jXPfkG
