### ISSUE TITLE
[FEATURE] Create a feature to make log files for Drifty

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#16]
**Is your feature request related to a problem? Please describe.**
A log file helps to better maintain what error has occurred or the request has been processed successfully.

**Describe the solution you'd like**
A feature to automatically generate log file when the application runs.

Contributors who want to take over this issue should at first comment below and then I will assign them with the task. Ensure that you will link this issue to your PR.

**Comment by thexahmed00** [comment]
I would like to work on this

**Comment by SaptarshiSarkar12** [comment]
Ok @thexahmed00 . Please link this issue to your PR.

**Comment by thexahmed00** [comment]
> Ok @thexahmed00 . Please link this issue to your PR.

Bro file will be created in log folder under project folder.If you restart IntelliJ you will see or you can use file explorer.

**Comment by SaptarshiSarkar12** [comment]
@thexahmed00 The file is not created after I rerun the app

**Comment by thexahmed00** [comment]
I’ll check

**Comment by SaptarshiSarkar12** [comment]
ok @thexahmed00 . Then,please make changes after pulling the latest code.

**Comment by SaptarshiSarkar12** [comment]
@thexahmed00 I have successfully removed dependencies (log4j) and have made a program myself which adds the logging functionality. [You may have a look at it](https://github.com/SaptarshiSarkar12/Drifty/blob/master/src/CreateLogs.java) and if required, you may modify that, through another PR.

**Comment by SaptarshiSarkar12** [comment]
@thexahmed00 I am closing this, but may reopen if you or anyone wants to modify Log functionality
