### ISSUE TITLE
set padding to the nav-bar items and download section

### ISSUE THREAD

**Issue by anantnipunge** [SaptarshiSarkar12/Drifty#164]
### Is your feature request related to a problem? Please describe.

the padding isn't good , because the irrelevant changes in style.css

### Describe the solution you'd like.

i will set padding to the nav-bar item.

### Application Version

v1.2.2

### Screenshots

before:

![image](https://user-images.githubusercontent.com/82041920/198192672-2d7ed962-d439-4047-9735-6b400c7274fd.png)

![image](https://user-images.githubusercontent.com/82041920/198192788-a4c18fa2-93a6-441b-b8f9-967dffc5a90b.png)

after:

![image](https://user-images.githubusercontent.com/82041920/198192582-8ffa7f51-0bc6-4d44-b5a5-4933df793a46.png)

![image](https://user-images.githubusercontent.com/82041920/198192814-4ec3cbe7-e875-4a03-8119-ba927b06088d.png)

### Additional information

please assign me this issue. @sap

**Comment by SaptarshiSarkar12** [comment]
Yeah sure, assigning you with the task. @anantnipunge .

**Comment by anantnipunge** [comment]
Okay thanks i will push the code.

**Comment by SaptarshiSarkar12** [comment]
> Okay thanks i will push the code.

👍
