### ISSUE TITLE
creating new about page 

### ISSUE THREAD

**Issue by anantnipunge** [SaptarshiSarkar12/Drifty#169]
### Is your feature request related to a problem? Please describe.

about section in home page doesn't look good so want to create new `about` page.

### Describe the solution you'd like.

keeping header and footer same just changing body part which redirect to the new about page

### Application Version

v1.2.2

### Screenshots

![image](https://user-images.githubusercontent.com/82041920/198815485-fba57dbc-4348-4a28-af1c-96f632d9045c.png)

**Comment by anantnipunge** [comment]
please assign me this issue @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge Please either remove the screenshot or add the screenshot instead of writing `Uploading image.png...`

**Comment by anantnipunge** [comment]
ok working on it.

**Comment by SaptarshiSarkar12** [comment]
> ok working on it. @SaptarshiSarkar12

👍 🚀
