### ISSUE TITLE
Add animation in Abouts Us

### ISSUE THREAD

**Issue by Shreyan-12345** [SaptarshiSarkar12/Drifty#170]
### Description

suround it with a box and add beautiful animation

### Application Version

v1.2.2

**Comment by Shreyan-12345** [comment]
pls assign me this task

**Comment by SaptarshiSarkar12** [comment]
Ok @Shreyan-12345 assigning you with the task.

**Comment by SaptarshiSarkar12** [comment]
You can join our discord server - https://discord.gg/DeT4jXPfkG @Shreyan-12345
