### ISSUE TITLE
Optimize Header Animation

### ISSUE THREAD

**Issue by IM-TECHNO** [SaptarshiSarkar12/Drifty#174]
### Description

Optimize Header Animation.

### Application Version

v1.2.2

**Comment by Burekslayer** [comment]
Hello, I would like to contribute to this issue, but I'm not sure what you mean exactly by optimizing?

**Comment by IM-TECHNO** [comment]
Hello this is actually an continuation of another PR that's being handled by me, refer to #171 . Thank you for your concern

**Comment by SaptarshiSarkar12** [comment]
As #174 is a pat of #171, so @IM-TECHNO needs to be assigned.
You may create any other issue regarding Drifty application itself, etc.

**Comment by SaptarshiSarkar12** [comment]
@IM-TECHNO How much work is done?

**Comment by SaptarshiSarkar12** [comment]
@IM-TECHNO Are you still working on the issue? Has the work been completed? Have you faced any problems?

**Comment by SaptarshiSarkar12** [comment]
> @IM-TECHNO Are you still working on the issue? Has the work been completed? Have you faced any problems?

Please respond else I shall close this issue.

**Comment by IM-TECHNO** [comment]
Hello, I'm currently doing my exams. Can you please wait for a few days ?


ps Sorry i didn't respond back to you.

**Comment by SaptarshiSarkar12** [comment]
> Hello, I'm currently doing my exams. Can you please wait for a few days ?
> 
> ps Sorry i didn't respond back to you.

Ok give your exam. I shall wait till then. @IM-TECHNO

**Comment by IM-TECHNO** [comment]
Hello, my exams are over. I'll start working. 

Thank you for your patience

**Comment by SaptarshiSarkar12** [comment]
I shall surely review it once I am free.

**Comment by SaptarshiSarkar12** [comment]
Closing this issue as inactive.
