### ISSUE TITLE
Fix Menu Items

### ISSUE THREAD

**Issue by IM-TECHNO** [SaptarshiSarkar12/Drifty#180]
### Description

Fix the menu items as it's not in the correct order per the site. Kindly assign this issue to me. 

### Application Version

v1.2.2

**Comment by SaptarshiSarkar12** [comment]
ok, assigning @IM-TECHNO

**Comment by IM-TECHNO** [comment]
Fixed. Kindly accept with hacktoberfest label.

**Comment by SaptarshiSarkar12** [comment]
> Fixed. Kindly accept with hacktoberfest label.

@IM-TECHNO please open a PR to my repo, not your forked repo. Else, how can I review it?

**Comment by IM-TECHNO** [comment]
My mistake. Kindly excuse.

**Comment by SaptarshiSarkar12** [comment]
> My mistake. Kindly excuse.

It's okay @IM-TECHNO .
