### ISSUE TITLE
creating separate pages for each nav-element

### ISSUE THREAD

**Issue by anantnipunge** [SaptarshiSarkar12/Drifty#183]
### Is your feature request related to a problem? Please describe.

it looks complex having everything in the same page and has high network load for all those different sections to load in one webpage. It is also harder to maintain such large html codes.

### Describe the solution you'd like.

to make it look more cool for user i would like to create new pages for each nav element. The website load time would also improve.

### Application Version

v1.2.2

### Additional information

please assign me this issue @SaptarshiSarkar12.

**Comment by SaptarshiSarkar12** [comment]
Sure @anantnipunge.

**Comment by anantnipunge** [comment]
thanks again woking on it. will submit it soon
@SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
> thanks again woking on it. will submit it soon @SaptarshiSarkar12

Welcome @anantnipunge

**Comment by SaptarshiSarkar12** [comment]
Closing this as the website will be revamped via #196 hence no more required.
