### ISSUE TITLE
[WEBSITE] Change the website to a Next js Application

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#196]
### Description

The website contains html, css and JavaScript files and is a normal website. But, I wish to change it to a React Application to include more features and easy maintenance as well as including some benefits of using React. The React App should look visually beautiful and appealing and should contain the same nav bar items and different pages for each of the nav bar items. The pages should at least contain the contents present now.

### Additional information

Please comment below if you wish to work on this issue and I shall assign you with the task.

**Comment by naveen13-06** [comment]
Hey @SaptarshiSarkar12 ,Iam new to open source and  I have been learning react for the past 2 weeks . Can I try this out?

**Comment by Agrim-Sharma174** [comment]
I also want to work on this issue, I will use Tailwind CSS & NextJs- a framework of ReactJs, which provides many benefits to the website like in SEO, or it helps in backend stuff too. This tech-stack will do wonders in terms of quality and easiness of building.

I can work alone too, but if anyone else wants to work along, we can work together and deliver the best website.
Thanks

**Comment by sayande2002** [comment]
I want to work on this project. I will use React Js with " Vanilla CSS " ( because it gives more flexibility ). Open to collaborating with anyone or can do it alone. I am also comfortable switching to any other tech stack according to Admin.

**Comment by SaptarshiSarkar12** [comment]
Okay, so all three of you are interested in working on this issue. You can collaborate among yourself and divide the task to make the development faster. I am assigning all three of you. Work on the issue, open the PR , and I shall review it. Note: The website needs to be responsive on almost all devices. Let me know if you agree with me @naveen13-06 @Agrim-Sharma174 @sayande2002 .

**Comment by Agrim-Sharma174** [comment]
Yeah, I am ready.
With tailwind CSS, there's no need to worry about responsiveness.

Also, I am well versed with NextJs, there's not a huge difference between NextJs & ReactJs, just it will be easier for routing, and other things we can discuss, I think we should connect,
Here's my Twitter id: https://twitter.com/Agrim_Sharma174
If required to DM

**Comment by naveen13-06** [comment]
Yeah, iam also ready to collaborate👍

**Comment by SaptarshiSarkar12** [comment]
Okay then @Agrim-Sharma174 start the work in collaboration with @naveen13-06 . Please use Tailwind CSS and Next.js. I have googled them and found them very useful and beautiful. 
@sayande2002 if you want, you can modify the website made by them once it gets reviewed and merged. If anyone faces any problem, let me know.

**Comment by SaptarshiSarkar12** [comment]
@Agrim-Sharma174 How much worl is done?

**Comment by Agrim-Sharma174** [comment]
Not much, because I was busy in an event at college

**Comment by SaptarshiSarkar12** [comment]
Ok @Agrim-Sharma174 once the basic site is made, you can open the PR and work on the rest. I shall review it.

**Comment by Agrim-Sharma174** [comment]
I'm sorry to let you know, but I will have to opt out of this project, I will not be able to proceed, the reason being, I am currently very busy with many works related to college, and events. In the last 4 days, I got very less time to work on this project, but again I can not fully devote myself, so someone else should get a chance to work.
Please unassign it from me at the moment, I can get back in 1-2 weeks if required.

**Comment by SaptarshiSarkar12** [comment]
> I'm sorry to let you know, but I will have to opt out of this project, I will not be able to proceed, the reason being, I am currently very busy with many works related to college, and events. In the last 4 days, I got very less time to work on this project, but again I can not fully devote myself, so someone else should get a chance to work. Please unassign it from me at the moment, I can get back in 1-2 weeks if required.

It's okay.
If @naveen13-06 or @sayande2002 or anyone else wants to contribute, please comment below and I will assign you. If no one gets assigned within 2 weeks, then @Agrim-Sharma174 would work on the issue. 
NOTE : You need to use Next.js and tailwind CSS.

**Comment by naveen13-06** [comment]
I would like to work on it. Since iam learning and trying it would take some time, is that ok for you? 
It would also be helpful if someone can help me with tailwind css

**Comment by SaptarshiSarkar12** [comment]
> I would like to work on it. Since iam learning and trying it would take some time, is that ok for you? It would also be helpful if someone can help me with tailwind css

Yes, you can work on it. You need to use Next.js and tailwind CSS. And you can collaborate with someone who knows tailwind CSS or you can refer the [documentation of Tailwind CSS](https://tailwindcss.com/docs/) . I shall be free after 20th March, so you have got a month's time. Learn Next.js and tailwind CSS and then you can work on it. Please open the Pull Request by 20th so that I can review once I am free.

**Comment by SaptarshiSarkar12** [comment]
@naveen13-06 How much work is done? Have you started?

**Comment by SaptarshiSarkar12** [comment]
> Hey @SaptarshiSarkar12, i have completed nearly 50% of the website. Will Complete within march 20👍

Great 👍 ! Keep doing!

**Comment by SaptarshiSarkar12** [comment]
Hi @naveen13-06 🖐!!
How much work is done? Has the website been completed?

**Comment by naveen13-06** [comment]
> Hi @naveen13-06 🖐!!
> How much work is done? Has the website been completed?

Hey @SaptarshiSarkar12 ,I have completed most of the work. The only remaining works are the animation and some errors during build process. Can you give me time till Sunday?

**Comment by SaptarshiSarkar12** [comment]
> > Hi @naveen13-06 raised_hand_with_fingers_splayed!!
> > How much work is done? Has the website been completed?
> 
> Hey @SaptarshiSarkar12 ,I have completed most of the work. The only remaining works are the animation and some errors during build process. Can you give me time till Sunday?

okay @naveen13-06 , that's great! 
You can go on with the work and open the Pull Request once it's done.
Thank you!

**Comment by SaptarshiSarkar12** [comment]
Hey @naveen13-06 , if you wish you can change the whole UI (the theme of the website). Also, you should make separate pages for each Navbar elements (like '/downloads', '/about', etc.). Make it beautiful as much as possible and making it responsive on most/all devices.

**Comment by JaiS99** [comment]
> > Hi @naveen13-06 🖐!!
> > How much work is done? Has the website been completed?
> 
> Hey @SaptarshiSarkar12 ,I have completed most of the work. The only remaining works are the animation and some errors during build process. Can you give me time till Sunday?

Hi, if you'd like me to help, just ask.

**Comment by naveen13-06** [comment]
> > > Hi @naveen13-06 🖐!!
> > > How much work is done? Has the website been completed?
> > 
> > 
> > Hey @SaptarshiSarkar12 ,I have completed most of the work. The only remaining works are the animation and some errors during build process. Can you give me time till Sunday?
> 
> Hi, if you'd like me to help, just ask.

Hey, Thank you for asking . I am stuck with the animation part , can you help me with it?

**Comment by SaptarshiSarkar12** [comment]
Hey @JaiS99 and @naveen13-06 , if you want to discuss together on this issue, you both can [join our Discord server](https://discord.gg/DeT4jXPfkG) and discuss there. There are also more Web Devs to help you out.

**Comment by JaiS99** [comment]
> > > > Hi @naveen13-06 🖐!!
> > > > How much work is done? Has the website been completed?
> > > 
> > > 
> > > Hey @SaptarshiSarkar12 ,I have completed most of the work. The only remaining works are the animation and some errors during build process. Can you give me time till Sunday?
> > 
> > 
> > Hi, if you'd like me to help, just ask.
> 
> Hey, Thank you for asking . I am stuck with the animation part , can you help me with it?

Yes! sure, link me to your codebase and ill get started, you can even ping me on discord as gamingskull16 in the server.

**Comment by SaptarshiSarkar12** [comment]
> > > > > Hi @naveen13-06 raised_hand_with_fingers_splayed!!
> > > > > How much work is done? Has the website been completed?
> > > > 
> > > > 
> > > > Hey @SaptarshiSarkar12 ,I have completed most of the work. The only remaining works are the animation and some errors during build process. Can you give me time till Sunday?
> > > 
> > > 
> > > Hi, if you'd like me to help, just ask.
> > 
> > 
> > Hey, Thank you for asking . I am stuck with the animation part , can you help me with it?
> 
> Yes! sure, link me to your codebase and ill get started, you can even ping me on discord as gamingskull16 in the server.

@JaiS99 You can review #204 for the website.

**Comment by SaptarshiSarkar12** [comment]
@Agrim-Sharma174 @sayande2002 Please review #204 to provide more suggestions and help us to fix bugs early.
