### ISSUE TITLE
[DOCS] Update the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [SaptarshiSarkar12/Drifty#198]
### How would you improve the documentation? Please describe.

I would like to work on the README by making subtle changes to make it more appealing and easy on the eyes.
If its ok, do assign me to the issue

**Comment by SaptarshiSarkar12** [comment]
@the-amazing-atharva Yes you can make it more appealing and easy to read. Please also add a content section. 
I think you can create a **docs** folder inside **Website** folder and add separate pages for the README including more details and pictures to make it more user friendly. You can use [**AsciiDoc**](https://asciidoc.org/) to create documentation which I recommend and [**AsciiDoctor**](https://asciidoctor.org/) to convert them to **HTML** pages for the docs. I was thinking about it. I would appreciate if you work on this in the way I mentioned. If you face any problem, let me know.

**Comment by SaptarshiSarkar12** [comment]
@the-amazing-atharva Are you working on the docs? Have you started? How much is done?

**Comment by the-amazing-atharva** [comment]
> @the-amazing-atharva Are you working on the docs? Have you started? How much is done?

Hi sorry for the late reply
I am currently in 12th grade so my board exams are going on so I wont be able to give so much time for this, I was thinking some minor changes but its fine you can assign this issue to someone else

Thanks for considering me!

**Comment by SaptarshiSarkar12** [comment]
> > @the-amazing-atharva Are you working on the docs? Have you started? How much is done?
> 
> Hi sorry for the late reply I am very new to Github and its procedures as I am currently in 12th grade so my board exams are going on so I wont be able to give so much time for this, I was thinking some minor changes but its fine you can assign this issue to someone else
> 
> Thanks for considering me!

It's okay. I apologize for disturbing you. You can work on this when you will be free after your board exams end. I shall be free after 20th March, so you can still work on it if you want. Let me know if you agree with me.

**Comment by the-amazing-atharva** [comment]
> > > @the-amazing-atharva Are you working on the docs? Have you started? How much is done?
> > 
> > 
> > Hi sorry for the late reply I am very new to Github and its procedures as I am currently in 12th grade so my board exams are going on so I wont be able to give so much time for this, I was thinking some minor changes but its fine you can assign this issue to someone else
> > Thanks for considering me!
> 
> It's okay. I apologize for disturbing you. You can work on this when you will be free after your board exams end. I shall be free after 20th March, so you can still work on it if you want. Let me know if you agree with me.

No worries !
Thanks for understanding

**Comment by SaptarshiSarkar12** [comment]
Welcome

**Comment by SaptarshiSarkar12** [comment]
@ How much work is done? Have you started? 
If you wish, you can work only on the README part and I can work on the docs part as it is going to be a bit complex. Let me know what you wish to do.

**Comment by the-amazing-atharva** [comment]
Hi!!
+ Changed the structure for a better look
+ Updated the heading
+ Added bold to missing texts
+ Fixed a link

**Comment by SaptarshiSarkar12** [comment]
Ok @the-amazing-atharva . I shall review it on 20th March. Please wait till then.
