### ISSUE TITLE
[BUG] Non responsive design for IPad

### ISSUE THREAD

**Issue by itshypon** [SaptarshiSarkar12/Drifty#199]
### Describe the bug

When you open Drifty website in IPad Air or IPad Mini, the design collapses or website is non-responsive for that width and height.

### Steps To Reproduce

1. Go to website
2. Inspect element and change dimension to IPad

### Expected Behavior

Website must be responsive.

### Operating System

Windows

### Application Version

v1.3.0

### Screenshots

![image](https://user-images.githubusercontent.com/30335924/223702116-0b88404e-49f7-400c-9228-edce0969e9c9.png)

### Additional information

Unresponsiveness is also found in Nest Hub Max and foldable mobiles.

**Comment by SaptarshiSarkar12** [comment]
Okay @itshypon , thank you for the opening the issue. Do you want to work on this issue?

**Comment by itshypon** [comment]
@SaptarshiSarkar12 If someone else doesn't take this issue then I will reply back if I got time.

**Comment by SaptarshiSarkar12** [comment]
@itshypon do you want to work on it?
If anyone else wants to work, please comment below and I shall assign you with the task.

**Comment by itshypon** [comment]
@SaptarshiSarkar12 I have shared this issue with some people who are looking for their first contribution.

**Comment by SaptarshiSarkar12** [comment]
ok @itshypon . That's great :star_struck: !
More peoples should get involved in open-source!
Thank you !
