### ISSUE TITLE
[BUG] Add support for updating yt-dlp

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#215]
# Describe the bug
The Drifty executables released, contains yt-dlp (the program responsible for downloading YouTube videos) inside them. Whenever the user tries to download YouTube videos, Drifty passes the YouTube video link to yt-dlp which then downloads it. If yt-dlp is not on the latest version, it throws an error (shown in the image below 👇).

# Screenshots
![Yt-dlp Error](https://user-images.githubusercontent.com/71605411/245838286-36e09234-c2e0-4429-abc1-80d2caa72179.JPG)

# Additional information
If the yt-dlp update command (```yt-dlp -U```) is run to update itself before initiating the download process, the error might be avoided.
Check out [```yt-dlp GitHub repository```](https://github.com/yt-dlp/yt-dlp) to learn more about it.

**Comment by SaptarshiSarkar12** [comment]
If anyone wants to work on this issue, please comment your name here and I shall assign you.

**Comment by pushkaraj2007** [comment]
Hey @SaptarshiSarkar12 

Can you please explain a bit more about this issue?

**Comment by SaptarshiSarkar12** [comment]
> Hey @SaptarshiSarkar12
> 
> Can you please explain a bit more about this issue?

@pushkaraj2007 Yeah, sure. The **Drifty executables** released, contains **yt-dlp (the program responsible for downloading _YouTube_ videos) inside them**. Whenever the _user tries to download YouTube videos_, Drifty passes the **YouTube video link to yt-dlp** which then _downloads it_. If yt-dlp is **not on the latest version**, it throws an error (shown in the image below 👇).

![Yt-dlp Error](https://user-images.githubusercontent.com/71605411/245838286-36e09234-c2e0-4429-abc1-80d2caa72179.JPG)

This error can be solved by passing the **```-U```** flag to ```yt-dlp``` to **update itself** before downloading the **YouTube video**. Hence, *no* error will henceforth be thrown.

You can check out [```yt-dlp project```](https://github.com/yt-dlp/yt-dlp) to learn more about it.

**Comment by pushkaraj2007** [comment]
@SaptarshiSarkar12 

Thanks!

So, what needs to be fix to solve this issue?

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12
> 
> Thanks!
> 
> So, what needs to be fix to solve this issue?

@pushkaraj2007 Whenever the user provides a YouTube video link to Drifty, Drifty should check and update yt-dlp (if it's not on the latest version) before initiating the download process. The command to update yt-dlp is ```yt-dlp -U```. You also need to check if that work or not.

**Comment by SaptarshiSarkar12** [comment]
@pushkaraj2007 Do you want to work on this issue?

**Comment by SaptarshiSarkar12** [comment]
> @pushkaraj2007 Do you want to work on this issue?

@pushkaraj2007 Please respond.

**Comment by pushkaraj2007** [comment]
> > @pushkaraj2007 Do you want to work on this issue?
> 
> @pushkaraj2007 Please respond.

@SaptarshiSarkar12 

I would like to, but TBH I don't have much experience with using Java.

I noticed this after asking you the question that Java is being used in this project.

**Comment by SaptarshiSarkar12** [comment]
> > > @pushkaraj2007 Do you want to work on this issue?
> > 
> > 
> > @pushkaraj2007 Please respond.
> 
> @SaptarshiSarkar12
> 
> I would like to, but TBH I don't have much experience with using Java.
> 
> I noticed this after asking you the question that Java is being used in this project.

Ok @pushkaraj2007 . If you want, you may try this out.

**Comment by SaptarshiSarkar12** [comment]
I shall work on this issue as no one is interested to work on this.
