### ISSUE TITLE
[FEATURE] Add support for downloading Instagram videos and photos

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#216]
# Is your feature request related to a problem? Please describe.
Currently, Drifty does not support **downloading Instagram videos and photos**, hence, this has been a _limitation_ of Drifty.

# Describe the solution you'd like.
Adding the support for **_downloading Instagram videos and photos_**.

**Comment by SaptarshiSarkar12** [comment]
If anyone wants to work on this issue, please comment your name here and I shall assign you.

**Comment by siddarthpai** [comment]
hey! can I work on this

**Comment by SaptarshiSarkar12** [comment]
> hey! can I work on this

@siddarthpai Yes, you can. I am assigning you with the task.

**Comment by SaptarshiSarkar12** [comment]
@siddarthpai How much work is done? Have you started working?

**Comment by SaptarshiSarkar12** [comment]
> @siddarthpai How much work is done? Have you started working?

@siddarthpai Please respond.

**Comment by SaptarshiSarkar12** [comment]
@siddarthpai Please let me know about your progress.

**Comment by Kartikesh001** [comment]
to add this feature u will ....have use a third party app and also it would require a API..i guess.

**Comment by SaptarshiSarkar12** [comment]
> to add this feature u will ....have use a third party app and also it would require a API..i guess.

@Kartikesh001 ok, so, would you like to work on this issue?

**Comment by abhishekkumarXD** [comment]
Hi @SaptarshiSarkar12, I would like to work on this issue.

**Comment by SaptarshiSarkar12** [comment]
> Hi @SaptarshiSarkar12, I would like to work on this issue.

Ok @abhishekkumarXD, you can work on this as @siddarthpai is not responding.

**Comment by abhishekkumarXD** [comment]
Hi @SaptarshiSarkar12, thanks for assigning me this issue. I have created a pull request (#223) that addresses the issue. Please review it and let me know if there are any problems.

**Comment by SaptarshiSarkar12** [comment]
> Hi @SaptarshiSarkar12, thanks for assigning me this issue. I have created a pull request (#223) that addresses the issue. Please review it and let me know if there are any problems.

Thank you for creating the PR @abhishekkumarXD ! I shall check this PR by tomorrow (and let you know if it has any problems) as I am busy now.
