### ISSUE TITLE
[FEATURE] Make docker image for drifty app

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#218]
# Is your feature request related to a problem? Please describe.
There is **no docker image of the Drifty application** presently, hence, _people who wants to try the app or use it through docker_, cannot have their wish fulfilled.

# Describe the solution you'd like.
**Two docker files should be created which will start the Drifty app in _CLI_ or in _GUI_ mode**. The user should be able to _interact with both the GUI and the CLI_. A **docker compose** file might help in maintaining **two docker files**.

**Comment by SaptarshiSarkar12** [comment]
If anyone wants to work on this issue, please comment your name here and I shall assign you.

**Comment by akshayamadhuri** [comment]
@SaptarshiSarkar12  I WOULD LIKE TO WORK ON THIS ISSUE

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 I WOULD LIKE TO WORK ON THIS ISSUE

@akshayamadhuri Sure, you can work on this. I am assigning you with the task.

**Comment by Ankit8848** [comment]
@SaptarshiSarkar12 hey, can you assign to me . Only  docker image needed ?

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 hey, can you assign to me . Only docker image needed ?

@akshayamadhuri

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 hey, can you assign to me . Only docker image needed ?

@akshayamadhuri Are you working on this? How much is done? 
If @akshayamadhuri is not willing to work/ is not working, then you (@Ankit8848) can be assigned. Let us wait for @akshayamadhuri 's reply.

**Comment by Ankit8848** [comment]
@SaptarshiSarkar12 yeah, sure . I will wait for his reply .

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 yeah, sure . I will wait for his reply .

Great 👍!

**Comment by akshayamadhuri** [comment]
@SaptarshiSarkar12   you can assign @Ankit8848

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 you can assign @Ankit8848

@akshayamadhuri Ok, thanks for your cooperation.
@Ankit8848 You can start working on this. I a assigning you with the task. 
**Note: You need to use _docker-compose_ file to manage two Dockerfiles for CLI and GUI respectively.**

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 hey, can you assign to me . Only docker image needed ?

@Ankit8848 Have you started working on the issue? How much is done?

**Comment by Ankit8848** [comment]
@SaptarshiSarkar12  Yeah,sure bro.

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 Yeah,sure bro.

Ok. @Ankit8848 When are you planning to open a PR?

**Comment by Ankit8848** [comment]
@SaptarshiSarkar12 bro, i have sent msg  in your discord about facing issue? Can you help me out ?

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 bro, i have sent msg in your discord about facing issue? Can you help me out ?

Yeah, sure 👍

**Comment by SaptarshiSarkar12** [comment]
@Ankit8848 How much work is done? Has the error got resolved?

**Comment by SaptarshiSarkar12** [comment]
> @Ankit8848 How much work is done? Has the error got resolved?

@Ankit8848 Please respond.

**Comment by SaptarshiSarkar12** [comment]
@Ankit8848 Do you want to work on this issue? You seem to be inactive for a long time.

**Comment by SaptarshiSarkar12** [comment]
@Ankit8848 no longer wants to work on this. So, @akshayamadhuri **do you want to work on this issue?**

**Comment by akshayamadhuri** [comment]
@SaptarshiSarkar12  sure, i will try it again

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 sure, i will try it again

Thank you @akshayamadhuri! I am assigning you with the task.

**Comment by SaptarshiSarkar12** [comment]
@akshayamadhuri is no longer willing to work on this issue. So, **if anyone wants to work on this, please comment below.**

**Comment by Surya-KN** [comment]
hello, I will try to work on this

**Comment by SaptarshiSarkar12** [comment]
Ok @Surya-KN! You can start working on this issue. I am assigning you with the task.

**Comment by paliwal999harsh** [comment]
Hello @SaptarshiSarkar12 

I would like to work on this issue.
If this issue is not assigned to anybody, let me know.

Thanks

**Comment by SaptarshiSarkar12** [comment]
> Hello @SaptarshiSarkar12
> 
> I would like to work on this issue. If this issue is not assigned to anybody, let me know.
> 
> Thanks

@paliwal999harsh Thank you for your interest. 
But, it has been already assigned to @Surya-KN and he is working on it.
You can join our discussion on this issue on our [discord server](https://discord.gg/DeT4jXPfkG).

**Comment by Sourav-Kumar-Panda** [comment]
Hey @SaptarshiSarkar12  
I would like to work on this issue.

**Comment by SaptarshiSarkar12** [comment]
@Sourav-Kumar-Panda This issue is being actively worked on by @Surya-KN and discussed in [our Discord server](https://discord.gg/DeT4jXPfkG). We are facing some issues regarding the **Dockerfile for Drifty GUI**. So, if you can help, please discuss your ideas in [our Discord server](https://discord.gg/DeT4jXPfkG).
