### ISSUE TITLE
[FEATURE] Change the Colour of Drifty Heading in the website

### ISSUE THREAD

**Issue by Vijaykv5** [SaptarshiSarkar12/Drifty#220]
### Is your feature request related to a problem? Please describe.

Make image of Drify as White instead of Blue as its Doesn't looks good in Blue background.
![Capture](https://github.com/SaptarshiSarkar12/Drifty/assets/94985341/c0d208c8-2c98-4e8a-842a-8b0c950aee07)

### Describe the solution you'd like.

Make it to white as it looks more Comfortable and Fit!
![Capture](https://github.com/SaptarshiSarkar12/Drifty/assets/94985341/4594119d-ce42-4904-9099-362d113f95e6)
 to Blue Background

**Comment by SaptarshiSarkar12** [comment]
Great idea 😃 @Vijaykv5 ! Do you want to work on this issue?

**Comment by Vijaykv5** [comment]
Yes I'm interested to work on it

**Comment by SaptarshiSarkar12** [comment]
> Yes I'm interested to work on it

Sure, you may go ahead 👍 @Vijaykv5 !
