### ISSUE TITLE
[BUG]  Web site broken link

### ISSUE THREAD

**Issue by EasyG0ing1** [SaptarshiSarkar12/Drifty#226]
### Describe the bug

See screenshot

### Steps To Reproduce

Go to web site, navigate off of home page then click on the Home button

### Operating System

MacOS

### Browser

Google Chrome

### Screenshots

<img width="646" alt="Screenshot 2023-07-14 at 8 25 55 AM" src="https://github.com/SaptarshiSarkar12/Drifty/assets/10106834/f48f4e48-7372-4aba-91bb-65762a46015d">

**Comment by SaptarshiSarkar12** [comment]
Thanks Michael (@EasyG0ing1) for raising the issue :smile:!
Do you like to work on it?

**Comment by Cvr421** [comment]
Hey can I work on these .

**Comment by SaptarshiSarkar12** [comment]
> Hey can I work on these .

Sure @Cvr421 ! You can work on this.

**Comment by Cvr421** [comment]
Ok thanks. I'll start working on that

**Comment by SaptarshiSarkar12** [comment]
@Cvr421 I think the error has gone (seems so from my end), after I re-deployed the website without making any notable changes in the code base. Please check if it's the same from your end.

**Comment by SaptarshiSarkar12** [comment]
Closing this issue as the error has got resolved (Verified by @Cvr421 in our discord server) by just re-deploying the Website.

**Comment by EasyG0ing1** [comment]
@SaptarshiSarkar12 Yes the whole site seems to be working quite well now. Even the stats images seem to be working now.

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 Yes the whole site seems to be working quite well now. Even the stats images seem to be working now.

That's great :star_struck: ! Thank you @EasyG0ing1 for the confirmation :grinning: .
