### ISSUE TITLE
[BUG] NumberFormatException after inputs

### ISSUE THREAD

**Issue by thexahmed00** [SaptarshiSarkar12/Drifty#24]
**Exception Occur**

**To Reproduce**
1. run Drifty_CLI
2. give Inputs
3. choose either Y or N

**Expected behavior**
Should give download logs and Success and location of the file

**Screenshots**
![image](https://user-images.githubusercontent.com/58472920/193416446-5868ed12-bd56-42e3-a3df-594f6c423019.png)

**Comment by SaptarshiSarkar12** [comment]
Thanks @thexahmed00 for reporting the bug.
If anyone wants to work on this issue, please comment below and I shall assign you with the task.

**Comment by SaptarshiSarkar12** [comment]
@thexahmed00 are you using MAC OS?

**Comment by aryan-upa** [comment]
Hey, I am working on this. Can you assign this issue to me?

**Comment by SaptarshiSarkar12** [comment]
Sure @thexahmed00 . Assigning you with the task. Ensure that you will link this issue to your PR.

**Comment by SaptarshiSarkar12** [comment]
@aryan-upa How much is the work done? It is a severe problem, so needs an immediate fix.

**Comment by thexahmed00** [comment]
@SaptarshiSarkar12 revert commits in filedownloaded file cuz previously it was working fine

**Comment by SaptarshiSarkar12** [comment]
ok @thexahmed00 let me check

**Comment by SaptarshiSarkar12** [comment]
@aryan-upa I have successfully fixed this bug by replacing ```totalSize = Long.valueOf(openConnection.getHeaderField("content-length"));``` with ```totalSize = openConnection.getContentLength();``` .
Thus, I am closing this issue as it has been fixed.

**Comment by aryan-upa** [comment]
oh ok!
