### ISSUE TITLE
Decluttering Home Page: Avoid Displaying All Users

### ISSUE THREAD

**Issue by PriyansuMaurya** [SaptarshiSarkar12/Drifty#252]
### Is your feature request related to a problem? Please describe.

Showing all the users on landing page makes the home page cluttered.

![image](https://github.com/SaptarshiSarkar12/Drifty/assets/101447544/d0b2bc8e-b9b8-48a3-ba50-e6a626b060ab)

### Describe the solution you'd like.

I present you 2 options

1. Create a separate page for contributors and add a link for the page in the footer.

![image](https://github.com/SaptarshiSarkar12/Drifty/assets/101447544/0c5b0c4d-9d6a-496f-9014-77dc0449ae26)

2. Show only **top 5** contributors with **more** button which when clicked will direct to the this [link](https://github.com/SaptarshiSarkar12/Drifty/graphs/contributors) 

Don't worry about this 

![image](https://github.com/SaptarshiSarkar12/Drifty/assets/101447544/dd8628e1-d94d-45df-9486-c399a5c15fd5)

I will find a way to add this.

**Comment by SaptarshiSarkar12** [comment]
@PriyansuMaurya Thank you for opening the issue!
**_The second option will be better._** 
Having a whole webpage full of contributors' images does not make sense and would also increase the network payload.
**Do you like to get assigned on this issue?**

**Comment by SaptarshiSarkar12** [comment]
> Yes, I would love to work on this issue.

Okay @PriyansuMaurya. You are assigned!
If you want, you can discuss on this issue on [our discord server](https://discord.gg/DeT4jXPfkG).
