### ISSUE TITLE
can add the image of Drifty working on the website itself 

### ISSUE THREAD

**Issue by Shashwat0227** [SaptarshiSarkar12/Drifty#26]
**Describe alternatives you've considered**
Adding background image to the website of Drifty.

**Comment by Shashwat0227** [comment]
can add background img to the site of the working of drifty to the site itself

**Comment by SaptarshiSarkar12** [comment]
Yes @Shashwat0227 you can.

**Comment by SaptarshiSarkar12** [comment]
@Shashwat0227 do you want to work on this issue?

**Comment by Shashwat0227** [comment]
yes i will do it for sure

**Comment by SaptarshiSarkar12** [comment]
Ok @Shashwat0227 . Please make sure that you will link this issue to your PR.
