### ISSUE TITLE
[FEATURE] Add support for downloading Spotify songs

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#274]
### Is your feature request related to a problem? Please describe.

At present, Drifty is not capable of downloading Spotify songs from the users' favourite artists.

### Describe the solution you'd like.

I would wish to have a feature added to Drifty so that it can download Spotify songs. If it is possible, no login credentials should be required for downloading Spotify songs. If you have any better ideas, please let me know.

### Additional information

Those who wish to work on this issue, please comment down below. I will assign you with the task.

**Comment by Arush04** [comment]
Hi, @SaptarshiSarkar12 I would like to contribute!

**Comment by SaptarshiSarkar12** [comment]
As @Arush04 has expressed his interest in the issue earlier, so, I would assign @Arush04 .
@sinchana06 can make changes after @Arush04 's PR gets merged.

**Comment by SaptarshiSarkar12** [comment]
@Arush04 no longer wants to work on this issue. So, I am assigning the task to @sinchana06.

**Comment by Priyanshu-bit** [comment]
@SaptarshiSarkar12 I would like to contribute!

**Comment by SaptarshiSarkar12** [comment]
If @sinchana06 does not want to work on this issue, then I can assign you (@Priyanshu-bit). Let's wait for his/her reply

**Comment by sinchana06** [comment]
I will work on it.

**Comment by SaptarshiSarkar12** [comment]
> I will work on it.

Okay @sinchana06. You (@sinchana06) can start working.
After @sinchana06's Pull Request gets merged, you (@Priyanshu-bit) can make changes if you want via another PR.
Meanwhile, you (@Priyanshu-bit) can join [our discord server](https://discord.gg/DeT4jXPfkG) to get updates on this project.

**Comment by neenad99** [comment]
Hi can i contribute to this issue?

**Comment by SaptarshiSarkar12** [comment]
@neenad99 Sorry, this issue is being actively worked on by @sinchana06.
