### ISSUE TITLE
[FEATURE] Option to preserve original file name and extension.

### ISSUE THREAD

**Issue by Anurag-Bharati** [SaptarshiSarkar12/Drifty#28]
**Is your feature request related to a problem? Please describe.**
Naming a file everytime is a bit inconvenient for me. Sometimes, I'd like to preserve the original file name. Having a default naming and manual naming option would be handy.

**Describe the solution you'd like**
A simple name scrap function for the file name would be preferable. This function takes a link as a String and searches for the file name (including its extension). If found, It displays and assigns the name to a variable. If this process fails, then the manual option is shown. The user can also change the file name later.

**Describe alternatives you've considered**
I had also thought about naming the file with the current DateTime. Since every assignment is unique, it can be a default name.

**Comment by SaptarshiSarkar12** [comment]
Great feature inclusion idea @Anurag-Bharati . Thanks for this.
If anyone wants to work on this issue, please comment below and I shall assign you with the task.

**Comment by m9m** [comment]
This is implemented since [Pulll reuest 22](https://github.com/SaptarshiSarkar12/Drifty/pull/22). Leave the filename option blank, and the default filename from the download link will be preserved. However, there is not an option to name based off the current time.

**Comment by SaptarshiSarkar12** [comment]
Ok @m9m . Then, the PR #29 is going to enable the option to choose whether to preserve the file name or not.
