### ISSUE TITLE
[FEATURE] Add a features section in the Website

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#281]
### Is your feature request related to a problem? Please describe.

At present, the website does not show the features Drifty has. So, some users do not even feel like trying the product or even reporting bugs or asking to add features.

### Describe the solution you'd like.

A features section in the homepage of the website can be made, which will show the best features Drifty has. There should be proper icons/symbols beside the name of the features (if possible) along with demo videos or gif or screenshots.
The features can be :
- **It's Free and Open-Source**
- **Faster Downloading of files** : Parallel downloading of files' part makes the download faster
- **Support for downloading videos from YouTube, Instagram, etc.**
- **Available both in GUI and CLI mode** - Drifty has both CLI and GUI mode. So, it can be used anywhere as CLI or as GUI according to the requirements of the user.

....and many more!

### Additional information

If anyone wishes to work on this issue, feel free to comment below and I will assign you the task.

**Comment by anevski-stefan** [comment]
I want to work on this issue @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
@anevski-stefan Yes, you can work on this issue. I am assigning the task to you.

**Comment by anevski-stefan** [comment]
I created a pull request @SaptarshiSarkar12 . Please see it when give me feedback. If something needs to be changed also tell me.

**Comment by SaptarshiSarkar12** [comment]
Okay @anevski-stefan . Let me review it.
