### ISSUE TITLE
[FEATURE] Add Settings menu for Drifty GUI

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#282]
### Is your feature request related to a problem? Please describe.

Presently, Drifty GUI does not have any option to set preferences like Last Download folder, Auto-Paste link etc.

### Describe the solution you'd like.

A settings window can be created which will contain the list of preferences with a checkbox and the preferences can be set accordingly using the `Preferences` and `AppSettings` class.

### Additional information

Anyone who wish to work on this issue, feel free to comment below and I will assign you with the task.

**Comment by SaptarshiSarkar12** [comment]
Sure @Rajeshkeshoju, you can start working on this issue. I am assigning you with the task.

**Comment by Rajeshkeshoju** [comment]
@SaptarshiSarkar12, Could you list the prefs required for the settings menu precise.

**Comment by SaptarshiSarkar12** [comment]
@Rajeshkeshoju The preferences to be set are -
- **Downloads Folder**
- **App Theme / Background Colour** (_We have to discuss on this_)
- **Enable/Disable Auto-Paste link option**

If you have anything else to add, please let me know.

**Comment by SaptarshiSarkar12** [comment]
@Rajeshkeshoju Have you started working on it? Did you face any problem?

**Comment by SaptarshiSarkar12** [comment]
As @Rajeshkeshoju is not responding and is inactive, so, @kavyarishi19 can work on this issue. I am assigning the task to @kavyarishi19.

**Comment by SaptarshiSarkar12** [comment]
You can discuss on the changes you wish to bring in [our Discord server](https://discord.gg/DeT4jXPfkG).

**Comment by SaptarshiSarkar12** [comment]
@kavyarishi19 How much work is done? Did you face any problem?

**Comment by SaptarshiSarkar12** [comment]
@kavyarishi19 Do you still wish to work on it? You seem to be inactive for a long period of time.

**Comment by the-shivam-gupta** [comment]
can you provide a sample screenshot so as to get a clear understanding of the issue? @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta A **settings** window needs to be created which will set some settings for Drifty. It will look something like this :point_down: 
![SETTINGS](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/a615ac8f-2a5c-4692-b76e-5aec88f9ca78)

For **Theme**, Dark theme will be a dark blue gradient and for Light theme, it will be as it is present now. The buttons will also be dark (Need to think on this).
If you have any more setting options, you think we can set, please mention those.

**Comment by the-shivam-gupta** [comment]
So you basically need a new page in which all these things should be added right?

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta Yeah, it should be a part of Drifty GUI application - it must be a separate window.

**Comment by the-shivam-gupta** [comment]
Ok, I have tried to run your website but it's the mixture of next and Java I think and due to which I won't get a clear understanding of where and which IDE should I use. Basically I use codespaces to contribute to open source. So can u guide me a little about that?

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta You should `cd` into the **Website** directory and then run :point_down: 
- `npm ci`
- `npm run dev`
- Open [`http://localhost:3000`](http://localhost:3000)

**Comment by the-shivam-gupta** [comment]
![image](https://github.com/SaptarshiSarkar12/Drifty/assets/109647722/2bfbbf61-c773-4260-91b1-a7594d5e4253)

**Comment by the-shivam-gupta** [comment]
I tried to resolve this by updating the npm package and still got the same error.

**Comment by the-shivam-gupta** [comment]
Do you want it like this: 

![image](https://github.com/SaptarshiSarkar12/Drifty/assets/109647722/92c5c0c2-6be9-4d9d-b999-46795be8206a)

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta Please note that the **settings** window should be a part of **Drifty GUI application** and it has nothing to do with the website.

**Comment by the-shivam-gupta** [comment]
path: src/main/java/GUI
Do I have to work in this?

**Comment by SaptarshiSarkar12** [comment]
Yes, you need to create a **JavaFX Application window** in **`src/main/java/GUI/Forms`** directory.
@the-shivam-gupta Do you want to work on this issue?

**Comment by the-shivam-gupta** [comment]
Ya assign it to me

**Comment by SaptarshiSarkar12** [comment]
Okay @the-shivam-gupta. Thank you for your interest in working on this issue :smile:!

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta 
- Using VS Code will not help. You should at least use **[IntelliJ Idea Community Edition](https://www.jetbrains.com/idea/)**.
- Please note that it is a JavaFX App. So, you should not use any AWT components otherwise the build will fail.

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta Did you face any problem? Were you able to do the work?

**Comment by the-shivam-gupta** [comment]
Sorry for the gap in between I have been doing other works so I won't give time for this issue and will start working on it now.

**Comment by SaptarshiSarkar12** [comment]
It's okay @the-shivam-gupta.

**Comment by the-shivam-gupta** [comment]
when I'm trying to run the GUI application on my PC I'm encountering an error:

![image](https://github.com/SaptarshiSarkar12/Drifty/assets/109647722/ce615caf-8c68-43b6-b31b-d0aefaed40c3)

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta According to [this answer](https://answers.microsoft.com/en-us/windows/forum/all/msvcp140dll-missing/38d88c97-0178-4fc1-be73-14553a1336ce), you need to install Visual Studio C++ Redistributable to run the GUI application. By default it is installed in most windows machine. But in some machines, it might not have been installed.
You can download the file and install it from [here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170).

**Comment by SaptarshiSarkar12** [comment]
> when I'm trying to run the GUI application on my PC I'm encountering an error. Also, tried to reinstall and run but the error remains the same:
> 
> ![image](https://private-user-images.githubusercontent.com/109647722/289274114-ce615caf-8c68-43b6-b31b-d0aefaed40c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzk4NDQsIm5iZiI6MTcwMjM3OTU0NCwicGF0aCI6Ii8xMDk2NDc3MjIvMjg5Mjc0MTE0LWNlNjE1Y2FmLThjNjgtNDNiNi1iMzFiLWQwYWVmYWVkNDBjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxMTEyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGUyZTQ5NmNmODYxMDg5Nzk1ZDNhZDcwZGNiYjBjMTAyOWUxZDQxYTFhZTc3Mjg3OWRhM2QzMjFiNTk5ZmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h0dCdZ4CzpgOPxrHkVghva_TJa2Pbk6iXAyL6SFFoEE)

@the-shivam-gupta Has this issue been solved by the solution I told you?

**Comment by the-shivam-gupta** [comment]
not yet

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta Can you please check [**this guide**](https://www.graalvm.org/latest/docs/getting-started/windows/#install-visual-studio-build-tools-and-windows-sdk) and see if it works for you?

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta Have you started working on this issue? You seem to be inactive for some time.

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta Please reply.

**Comment by SaptarshiSarkar12** [comment]
Okay. I will make this issue open to all. I am unassigning you. If anybody wants to contribute, please comment below.

**Comment by ziad-ashraf7** [comment]
> Yes, you need to create a **JavaFX Application window** in **`src/main/java/GUI/Forms`** directory. @the-shivam-gupta Do you want to work on this issue?
hey @SaptarshiSarkar12 , i looked into the repo path and didn't actually find the path that you have mentioned 
instead it i found this **`Drifty\GUI\src\main\java\gui`** is that what you mean ? 
and fro the `\forms` directory it's not already made in the `\gui` directory, should I make it by myself?

**Comment by SaptarshiSarkar12** [comment]
@ziad-ashraf7 At first, thank you for your interest in this issue 😁.
Sorry for the confusion in paths. The project structure has changed a lot.
So, you'll need to create a Java class in `Drifty/GUI/src/main/java/ui/` directory. You can name it `Settings.java`. 
For building the window (Technically, it is called `JavaFX Stage`) You can use the `getStage()` method of `Constants.java` class (in `Drifty/GUI/src/main/java/gui/support/` directory) by passing the parameters as `"Settings"` and `false`. If you need further information, please let me know 😀.

**Comment by ziad-ashraf7** [comment]
@SaptarshiSarkar12 Thank you for responding, I jsut wanted to work on this issue and i have some questions :
1 - is the the color base of the dark theme and the light theme ?
2 - what is the main job for Auto-Paste buuton ? i tried to make it checked and unchecked and it seems there no different.
3 - is the settings page should contain a word "Settings" with big font in the center of the page ? 
4 - is it ok if i edited the design you have mentioned before with other design ?
5 - what about if i wanted to discuess any thing in the issue with you .... am i able to do that on the discord server , or here ??
after this , i will be happy if you assigned this issue for me ..😄.

**Comment by SaptarshiSarkar12** [comment]
1. The background colour of the current Drifty GUI, is of light theme (Even the background colour of the image of **Settings** window shown, is of light theme). You need to choose a gradient of colours for the dark theme. For choosing gradient colours, you can utilise [this website](https://cssgradient.io/).
2. I think you haven't understood how the **Auto-Paste** button works. See the below video. 

     [Screencast from 2024-06-15 14-52-10.webm](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/6a4bd874-1272-4f4f-8f1a-6f145b1d2e58)
3. No, the word **"Settings"** will be the window name and must not be present inside the window (Scene) itself.
4. Yeah, you can change that.
5. It must be in the **"Edit"** menu.
6. Yes, you can discuss in the **`#drifty`** channel.

@ziad-ashraf7 Thank you for your interest in working on this issue :smile:.
I am assigning this issue to you.

**Comment by SaptarshiSarkar12** [comment]
@ziad-ashraf7 The working part of the **Auto-Paste** button is present here :point_down: 
https://github.com/SaptarshiSarkar12/Drifty/blob/ba3839859480ff516cf6efc85e5d01682775d6d6/GUI/src/main/java/main/Drifty_GUI.java#L74-L84
and it is added to the UI in this method :point_down: 
https://github.com/SaptarshiSarkar12/Drifty/blob/ba3839859480ff516cf6efc85e5d01682775d6d6/GUI/src/main/java/ui/MainGridPane.java#L157-L161

Let me know if you have any further questions :smiley:.
