### ISSUE TITLE
[FEATURE] Add Support for Download History in Drifty CLI

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#283]
### Is your feature request related to a problem? Please describe.

Drifty CLI lacks a feature that can detect previously downloaded files or processed links. Therefore, it cannot prompt the user to select a different filename or accept the generated one. The user will not receive any warning if they download the same file from the same link more than once.

### Describe the solution you'd like.

Drifty GUI already has a feature to check for previously processed links or previously downloaded links. The CLI should also utilise this feature to serve the user better. Whenever the link is received, Drifty CLI should check for any previously downloaded links or processed links and provide a warning accordingly.

### Additional information

If anyone wants to work on this issue, please feel free to comment below and I will assign you with the task.

**Comment by Abhishek2nayak** [comment]
hey @SaptarshiSarkar12 I would like to work on this issue. please assign me this issue.

**Comment by SaptarshiSarkar12** [comment]
Sure @Abhishek2nayak! I am assigning the task to you.

**Comment by SaptarshiSarkar12** [comment]
@Abhishek2nayak How much is done? Did you start working on it? did you face any problem?

**Comment by Abhishek2nayak** [comment]
@SaptarshiSarkar12 yeah I started working on it . and i hope this will fixed soon .

**Comment by SaptarshiSarkar12** [comment]
@Abhishek2nayak Okay. That's great :+1:
