### ISSUE TITLE
[FEATURE] Add ANSI Colours to the Drifty CLI outputs

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#284]
### Is your feature request related to a problem? Please describe.

Currently, Drifty CLI does not print the output in coloured format according to the type of the output message (Warn, Info, and Error). So, the CLI interface does not look good and colourful.

### Describe the solution you'd like.

The Drifty CLI should use ANSI colors to display outputs based on their message type. The message type is determined by the Message Broker class in the Backend package. You can check some [ANSI colour codes here](https://www.w3schools.blog/ansi-colors-java).
The suggested colors for each message type are:
- **INFO**: Blue or Green
- **WARN**: Yellow
- **ERROR**: Red

If you prefer different colors, please let me know.

### Additional information

If anyone wants to work on this issue, please comment below and I will assign you with the task.
You can join [our Discord server](https://discord.gg/DeT4jXPfkG) to discuss on this issue.

**Comment by barkhaaroraa** [comment]
Hi could you assign me this issue

**Comment by SaptarshiSarkar12** [comment]
@barkhaaroraa Yes, you can work on this issue. I am assigning the task to the you.

**Comment by SaptarshiSarkar12** [comment]
@barkhaaroraa Did you face any problem while solving this issue? How much is done?

**Comment by barkhaaroraa** [comment]
I haven't started working on it yet because of some assignment deadlines etc. will start from monday.

**Comment by SaptarshiSarkar12** [comment]
@barkhaaroraa No problem. You can start working on this issue from monday.

**Comment by SaptarshiSarkar12** [comment]
@barkhaaroraa Have you started working on it? Did you face any problem?

**Comment by SaptarshiSarkar12** [comment]
@barkhaaroraa Please reply

**Comment by barkhaaroraa** [comment]
Hi, sorry for the late reply, I've been quite busy with my exams, which are scheduled until the 12th. As a result, I haven't had much time to focus on OS. However, I've been using my free moments to contribute to smaller, less time-consuming issues.
Regarding the specific issue, it's something entirely new to me. I've been dedicating my spare time to understanding the repository and conducting research about the issue and potential solutions. At this point, I haven't started working on it actively, but I plan to dive in as soon as my exams are over. Sorry for the delay.

**Comment by SaptarshiSarkar12** [comment]
Its okay. No problem. Sorry for the interruption.
@barkhaaroraa I shall be out of station from 11th October, 2023 to 27th October, 2023. So, their might be delay in merging your PR. I will try my best to find some time to solve any issues you face and review the PR once you are done. **Will that be okay for you?**

**Comment by weedertree** [comment]
could you assign me with this issue?

**Comment by barkhaaroraa** [comment]
Absolutely, I understand. Thank you for informing me. I'll make sure to have everything ready for your review after your return. Safe travels!

**Comment by SaptarshiSarkar12** [comment]
Thank you @barkhaaroraa for informing me.
If @weedertree still wishes to work on it, I can assign @weedertree.
Else, @barkhaaroraa can work on it once you are free. I have no problem with the delay in the completion of this issue.

**Comment by SaptarshiSarkar12** [comment]
@weedertree Do you still wish to work on it?

**Comment by weedertree** [comment]
> @weedertree Do you still wish to work on it?

yes, i can take care of that

**Comment by SaptarshiSarkar12** [comment]
Okay. Then, I am assigning the task to you (@weedertree).

**Comment by weedertree** [comment]
> Okay. Then, I am assigning the task to you (@weedertree).

surely!

**Comment by SaptarshiSarkar12** [comment]
@weedertree How much work is done? Did you face any problem?

**Comment by SaptarshiSarkar12** [comment]
As @weedertree is not responding and @J9414 has already opened a PR for this issue, so, the assignment has been removed from @weedertree and it has been now assigned to @J9414.

**Comment by J9414** [comment]
hello @SaptarshiSarkar12 Thanks for assignment, i am getting error on ES lint check, i did diffent chages to manage that but it is still there 

Is it because I am using eclips to edit ?  or it is something else that I am not getting, Please let me know

**Comment by SaptarshiSarkar12** [comment]
No. I haven't checked the error. I will do it before merge.
