### ISSUE TITLE
[FEATURE] Add About window for Drifty GUI

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#285]
### Is your feature request related to a problem? Please describe.

Drifty GUI's latest build lacks an about window with the essential links to the relevant resources, such as the GitHub project link, the contributors link, the docs link, the app version, and the discord server link. Therefore, the users cannot access the necessary information to contact the project maintainers and provide feedback, report issues, or request features.

### Describe the solution you'd like.

An **About** window can be added with links to resources as mentioned in the above section. This is going to benefit the users a lot.

### Additional information

- If anyone wants to work on this issue, please feel free to comment below and I will assign you with the task.
- You can also discuss on this issue in [our Discord server](https://discord.gg/DeT4jXPfkG).

**Comment by suryanshsoni120** [comment]
@SaptarshiSarkar12, I would like to contribute to this issue

**Comment by SaptarshiSarkar12** [comment]
Sure @suryanshsoni120 ! You can work on this issue. Thank you for your interest.
Assigning the task to you.

**Comment by SaptarshiSarkar12** [comment]
@suryanshsoni120 Did you face any problem while solving this issue? How much work is done?

**Comment by SaptarshiSarkar12** [comment]
Okay. @suryanshsoni120 If you face any issue or facing any problem in understanding the codebase, you can post your question in our Discord server.

**Comment by SAGARSINGH-1** [comment]
@SaptarshiSarkar12 Can you share demo GUI to work on that

**Comment by SaptarshiSarkar12** [comment]
Sorry @SAGARSINGH-1. 
@suryanshsoni120 is already working on this issue. You can join [our Discord server](https://discord.gg/DeT4jXPfkG) to know about the progress of the issue.
