### ISSUE TITLE
[BUG] Fix "Download Now" buttons in the Website

### ISSUE THREAD

**Issue by akinpinkman** [SaptarshiSarkar12/Drifty#287]
### Is your feature request related to a problem? Please describe.
The three "Download Now" buttons on Drifty's homepage are not equally placed. The one with "**Prefer the msi?**" at the bottom is higher than the others.

### Describe the solution you'd like.
I will align the "Download Now" button for Windows download, which is not in the same position as the others.

### Screenshots

![1](https://github.com/SaptarshiSarkar12/Drifty/assets/108457883/4405dc24-6141-4cfc-9a48-9841b9c386fd)

### Additional information
I can work on this issue myself, kindly assign it to me directly.

**Comment by charann29** [comment]
@akinpinkman  I'm interested in working on this issue. Could you please assign it to me if anyone is no one is working on it? I'll start investigating the problem and work on a potential solution. Thank you!

**Comment by akinpinkman** [comment]
@charann29 At the top right corner of the page you can see that the issue is assigned to me. And I am working on this myself, thank you for your interest.

**Comment by charann29** [comment]
Apologies @akinpinkman , new to open-source.

**Comment by SaptarshiSarkar12** [comment]
@charann29 Sorry, the issue has already been assigned to @akinpinkman.
You (@charann29) can work on some other unassigned issues. **Check [the unassigned issues here](https://github.com/SaptarshiSarkar12/Drifty/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee).**
