### ISSUE TITLE
[FEATURE] New hero section

### ISSUE THREAD

**Issue by akinpinkman** [SaptarshiSarkar12/Drifty#289]
### Is your feature request related to a problem? Please describe.

The current website's hero section is very old and unattractive. I can add a more professional-looking hero section.

### Additional information

I would like to personally take care of this feature if it is approved. Therefore please assign it to me directly.

**Comment by SaptarshiSarkar12** [comment]
@akinpinkman Thank you for this feature request :smile:! The nav bar looks good. You can start working on this issue.
We can discuss about the design of the navbar in our Discord Server.
