### ISSUE TITLE
[BUG] : Fixing delay time in download buttons

### ISSUE THREAD

**Issue by Tushar1323** [SaptarshiSarkar12/Drifty#291]
### Is your feature request related to a problem? Please describe.

When i hover on the button 🖱️ , then it take some time to scale itself.

### Describe the solution you'd like.

 I want to make this animmation smooth and perfect looking. Or Like a add Modern button intead of that .
I would like to personally take care of this feature if it is approved. Therefore please assign it to me directly.

**Comment by SaptarshiSarkar12** [comment]
@Tushar1323 Thank you for opening the issue!
I think we can have a modern button instead of changing the duration. What do you think?

**Comment by SaptarshiSarkar12** [comment]
I am assigning the task to you @Tushar1323.

**Comment by Tushar1323** [comment]
> @Tushar1323 Thank you for opening the issue! I think we can have a modern button instead of changing the duration. What do you think?

I absolutely agree! 👍🏽 A modern button would be a great addition, and it can enhance the overall user experience. I'll work on creating a sleek and stylish modern button .

**Comment by SaptarshiSarkar12** [comment]
> > @Tushar1323 Thank you for opening the issue! I think we can have a modern button instead of changing the duration. What do you think?
> 
> I absolutely agree! 👍🏽 A modern button would be a great addition, and it can enhance the overall user experience. I'll work on creating a sleek and stylish modern button .

Ok :+1:

**Comment by akinpinkman** [comment]
Hey there, I just wonder. What buttons are we talking about? @Tushar1323

**Comment by Tushar1323** [comment]
All type of button like Downloads button and many more ....
Tushar keshari

**Comment by Tushar1323** [comment]
But i stuck at some point

Tushar keshari

**Comment by SaptarshiSarkar12** [comment]
@Tushar1323 Please describe the issue you are facing.

**Comment by Tushar1323** [comment]
I am able to run the website in my local ...
Can you tell me how to run it ?

Tushar keshari

**Comment by SaptarshiSarkar12** [comment]
Okay @Tushar1323. Follow these steps -
- Go to `Website` directory
- Run `npm ci` to install the dependencies
- Run `npm run dev` to start the development server
- Open [`localhost:3000`](http://localhost:3000/) in your browser to see the live website

**Comment by Tushar1323** [comment]
I had done this but when i run npm c i it show [errore[](url)](url)
![error](https://github.com/SaptarshiSarkar12/Drifty/assets/99569848/2f173d03-2c50-4432-95df-472e9ce0cb4a)

**Comment by contactshivakumar** [comment]
> I had done this but when i run npm c i it show [errore](url) ![error](https://user-images.githubusercontent.com/99569848/272412368-2f173d03-2c50-4432-95df-472e9ce0cb4a.jpg)

Hi Tushar, please run npm the command "npm ci" from the "Website" directory.

**Comment by contactshivakumar** [comment]
> I had done this but when i run npm c i it show [errore](url) ![error](https://user-images.githubusercontent.com/99569848/272412368-2f173d03-2c50-4432-95df-472e9ce0cb4a.jpg)

Hi Tushar, the error is due to npm unable to find package.json. Please run the command "npm ci" from the "Website" directory

**Comment by SaptarshiSarkar12** [comment]
@Tushar1323 Yes, @contactshivakumar is correct. 
You need to run `npm ci` in **Website** directory. Please run `cd Website` to go into **Website** directory.

**Comment by Tushar1323** [comment]
Thanks, I will.

Tushar keshari

**Comment by Dharmik3** [comment]
Hello @SaptarshiSarkar12 Can I work on the same issue? I will improve the button design as well as card design with fixed height of card that will increase the look and feel of the site.

**Comment by SaptarshiSarkar12** [comment]
@Tushar1323 is already working on this issue. 

You (@Dharmik3) can create a new issue for the changes you want to bring and we can continue the discussion of those there.
I think the features' cards height need not be fixed. They look nice now.

**Comment by Moulendu-Chowley** [comment]
@SaptarshiSarkar12 is the button issue solved ?

**Comment by SaptarshiSarkar12** [comment]
@Moulendu-Chowley A PR (Pull Request) has already been created for this issue and it's currently being reviewed.
