### ISSUE TITLE
[BUG] Stats are not aligned properly on about page

### ISSUE THREAD

**Issue by accodes21** [SaptarshiSarkar12/Drifty#297]
### Describe the bug

The github stats images are not properly, they should be aligned in a centered manner. Also there should be a small gap between all these images to make them look refined.
I would like to work on this issue.

### Steps To Reproduce

1. Go to about page.
2. Update the css property for the images to make them centered vertically.

### Operating System

Windows

### Browser

Google Chrome

### Screenshots

Before changes:
![Screenshot (388)](https://github.com/SaptarshiSarkar12/Drifty/assets/101868279/b885a351-1107-4066-ae64-c087e12c7f1b)

After updates the page should look like this:
![Screenshot (389)](https://github.com/SaptarshiSarkar12/Drifty/assets/101868279/738521a8-9e23-41e9-b074-4cbae81da23c)

**Comment by SaptarshiSarkar12** [comment]
Thank you @accodes21 for the bug report!
Would you like to work on this issue?

**Comment by accodes21** [comment]
@SaptarshiSarkar12 Yes I would like to work on it

**Comment by SaptarshiSarkar12** [comment]
Ok @accodes21. I am assigning the task to you.
