### ISSUE TITLE
Fix: Features section fix

### ISSUE THREAD

**Issue by akinpinkman** [SaptarshiSarkar12/Drifty#299]
### Is your feature request related to a problem? Please describe.

The current "Features" section cards have different dimensions than each other, and this does not look professional.

### Describe the solution you'd like.

I will fix the alignment of the feature cards as shown below.

### Screenshots

![image](https://github.com/SaptarshiSarkar12/Drifty/assets/108457883/41af7131-c59b-4fa5-a4a6-ff402343b543)

**Comment by akinpinkman** [comment]
Also, I would like to work on this issue if it's approved. Kindly assign me.

**Comment by SaptarshiSarkar12** [comment]
Thank you for opening the issue! 
Sorry @akinpinkman, I like the cards dimension as present now - it takes the space as required and it looks good to me. So, I would not wish to have this fix.
What do you think?
Should I close this issue then?

**Comment by akinpinkman** [comment]
![image](https://github.com/SaptarshiSarkar12/Drifty/assets/108457883/9cdbcff6-d7c5-4c2e-9c73-cc1c7d2ee742)
I mean if it looks okay to you no problem for me. You can close this issue.

**Comment by SaptarshiSarkar12** [comment]
Okay. Thank you @akinpinkman.
