### ISSUE TITLE
[FEATURE] Add dynamic year copyright in the footer

### ISSUE THREAD

**Issue by rhnas110** [SaptarshiSarkar12/Drifty#307]
### Is your feature request related to a problem? Please describe.

Currently I saw the code in the footer of the website for the copyright year is still static, I want to add a dynamic year copyright in the footer of the website.

### Describe the solution you'd like.

I create a new variable to get dynamic year info, named const currentYear

### Screenshots

![image](https://github.com/SaptarshiSarkar12/Drifty/assets/51848196/f0878649-52c2-4cef-abb8-b8e5825a6229)
![image](https://github.com/SaptarshiSarkar12/Drifty/assets/51848196/1f2f60f3-c9b9-4794-b6ae-8ffc027545c9)

### Additional information

Can you take my advice and assign this task to me Sir @SaptarshiSarkar12 ? and I am new to open source contributions and I would love to contribute to your project! I also participated in Hacktoberfest2023.

**Comment by SaptarshiSarkar12** [comment]
@rhnas110 Thank you for raising this issue!
Yes, you can work on this issue. I am assigning the task to you.
