### ISSUE TITLE
[BUG] JNI ERROR

### ISSUE THREAD

**Issue by akshatjainei** [SaptarshiSarkar12/Drifty#33]
Error in the new release of Drifty 

*To Reproduce*
1. Go to 'https://github.com/SaptarshiSarkar12/Drifty/raw/master/Drifty_CLI.exe'
2. Download Drifty for Windows
3. See error

**Comment by SaptarshiSarkar12** [comment]
Thanks @akshatjainei for the bug report. If anyone wants to work on this bug, please comment below and I would assign you with the task.

**Comment by BoseSj** [comment]
Getting this while trying to download and install it.
![image](https://user-images.githubusercontent.com/58129377/193453468-4877de33-ff1c-4855-a15b-074eca17eb72.png)

**Comment by BoseSj** [comment]
I would like to work on this issue @SaptarshiSarkar12 . But first I need to understand it. Can you help me by telling me exactly what is the issue you r getting @akshatjainei  ? Is this that error faced while downloading? or something else?

**Comment by akshatjainei** [comment]
@BoseSj I got that error after I downloaded it , It said JNI error on CLI

**Comment by akshatjainei** [comment]
![Screenshot (105)](https://user-images.githubusercontent.com/93882347/193455789-373ffb5e-9f8b-45a9-aade-fce05785ef91.png)
@BoseSj

**Comment by SaptarshiSarkar12** [comment]
@BoseSj @akshatjainei Please check if the bug has been resolved by downloading the latest CLI executable present.

**Comment by SaptarshiSarkar12** [comment]
Have you checked @akshatjainei ?

**Comment by BoseSj** [comment]
@SaptarshiSarkar12 it is working fine in my system.

**Comment by akshatjainei** [comment]
@SaptarshiSarkar12 Yup works fine in my system as well

**Comment by BoseSj** [comment]
> Getting this while trying to download and install it. ![image](https://user-images.githubusercontent.com/58129377/193453468-4877de33-ff1c-4855-a15b-074eca17eb72.png)

@SaptarshiSarkar12 about this, I would like to update the documentation/installation instruction. I think its necessary to avoid confusion for the users.

**Comment by SaptarshiSarkar12** [comment]
> > Getting this while trying to download and install it. ![image](https://user-images.githubusercontent.com/58129377/193453468-4877de33-ff1c-4855-a15b-074eca17eb72.png)
> 
> @SaptarshiSarkar12 about this, I would like to update the documentation/installation instruction. I think its necessary to avoid confusion for the users.

@BoseSj Please see if this occurs now for v1.1.0.

**Comment by SaptarshiSarkar12** [comment]
> > > Getting this while trying to download and install it. ![image](https://user-images.githubusercontent.com/58129377/193453468-4877de33-ff1c-4855-a15b-074eca17eb72.png)
> > 
> > 
> > @SaptarshiSarkar12 about this, I would like to update the documentation/installation instruction. I think its necessary to avoid confusion for the users.
> 
> @BoseSj Please see if this occurs now for v1.1.0.

If yes, then please open a new issue and we would continue the discussion there.

**Comment by SaptarshiSarkar12** [comment]
Closing this issue as it has been fixed.

**Comment by SaptarshiSarkar12** [comment]
> > > Getting this while trying to download and install it. ![image](https://user-images.githubusercontent.com/58129377/193453468-4877de33-ff1c-4855-a15b-074eca17eb72.png)
> > 
> > 
> > @SaptarshiSarkar12 about this, I would like to update the documentation/installation instruction. I think its necessary to avoid confusion for the users.
> 
> @BoseSj Please see if this occurs now for v1.1.0.

@BoseSj Please respond. Does this occur?

**Comment by BoseSj** [comment]
The error you mean in CLI?

**Comment by SaptarshiSarkar12** [comment]
@BoseSj no, not about the error.


> > Getting this while trying to download and install it. ![image](https://user-images.githubusercontent.com/58129377/193453468-4877de33-ff1c-4855-a15b-074eca17eb72.png)
> 
> @SaptarshiSarkar12 about this, I would like to update the documentation/installation instruction. I think its necessary to avoid confusion for the users.

About this one.

**Comment by SaptarshiSarkar12** [comment]
> Getting this while trying to download and install it. ![image](https://user-images.githubusercontent.com/58129377/193453468-4877de33-ff1c-4855-a15b-074eca17eb72.png)

This one

**Comment by BoseSj** [comment]
Oh, yeah it did.

**Comment by SaptarshiSarkar12** [comment]
Then please open an issue for that. The doc also need to mention about this.

**Comment by BoseSj** [comment]
> > Getting this while trying to download and install it. ![image](https://user-images.githubusercontent.com/58129377/193453468-4877de33-ff1c-4855-a15b-074eca17eb72.png)
> 
> @SaptarshiSarkar12 about this, I would like to update the documentation/installation instruction. I think its necessary to avoid confusion for the users.

About that, I was proposing a change in the documentation.

**Comment by SaptarshiSarkar12** [comment]
> Then please open an issue for that. The doc also need to mention about this.

Please do it.

**Comment by BoseSj** [comment]
Ok I am on it.

**Comment by SaptarshiSarkar12** [comment]
@BoseSj please open an issue at first

**Comment by BoseSj** [comment]
Cool! I have.

**Comment by SaptarshiSarkar12** [comment]
> Cool! I have.

Ok , all discussions regarding that issue shal be made in #37 .
