### ISSUE TITLE
[BUG] Navbar is causing an bottom overflow in the website

### ISSUE THREAD

**Issue by Trickkyyy** [SaptarshiSarkar12/Drifty#334]
### Describe the bug

The Navigation bar sticky prop is causing an bottom overflow.

### Steps To Reproduce

Just scroll to the bottom of the page and keep scrolling.

### Expected Behavior

The Scrolling should stop at the footer

### Operating System

Windows 🪟

### Browser

Google Chrome

### Screenshots

![Overflow_drifty](https://github.com/SaptarshiSarkar12/Drifty/assets/119752462/a112d25a-ae87-40ae-97d6-9c009064e22f)
![Overflow_drifty2](https://github.com/SaptarshiSarkar12/Drifty/assets/119752462/a72a23a9-989d-4b38-9dc7-05852345fd18)

### Additional information

I already fixed the problem and will set up a pull request.

**Comment by SaptarshiSarkar12** [comment]
@Trickkyyy Thank you for opening the issue 😀!
I will check your PR shortly 🙂.
