### ISSUE TITLE
[BUG] Overflow at the bottom of the Contact Page

### ISSUE THREAD

**Issue by Trickkyyy** [SaptarshiSarkar12/Drifty#336]
### Describe the bug

The `<textarea>` in the Contact page is causing overflow at the bottom.
Since the `<textarea>` can be resized by the user.

When the  `<textarea>` gets  smaller the overflow  appears at the bottom of the page.
Another unwanted behavior is that by resizing the user can try to make the Form `<textarea>` scroll to infinity.

My suggestion is to make the  `<textarea>` fixed size,this will improve the overall quality of the user experience and not cause any unexpected behavior.

### Steps To Reproduce

1.Go to the Contact Page
2. Use the resizing button at the bottom right corner of the `<textarea>`
3. Make the `<textarea>` smaller and an overflow appears.

### Operating System

Windows 🪟

### Browser

Google Chrome

### Screenshots

![overflow_contacts](https://github.com/SaptarshiSarkar12/Drifty/assets/119752462/9e5b0eb4-6613-4bc9-9329-82aeb10a2e64)

**Comment by SaptarshiSarkar12** [comment]
Thank you for opening this issue 😀 @Trickkyyy!
I will check your PR shortly.
