### ISSUE TITLE
[BUG]: Website is not responsive for devices for 280px - 320px dimension

### ISSUE THREAD

**Issue by the-shivam-gupta** [SaptarshiSarkar12/Drifty#350]
### Description

The website is not responsive for small devices starting from 280px and also for 320 px.

![image](https://github.com/SaptarshiSarkar12/Drifty/assets/109647722/60721d0a-778a-4970-894a-85e16f5feb09)
![image](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/83b60857-b852-494b-b1a1-df198626045a)

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta The problem also occurs for **280 x 653 px Galaxy Fold** display.
@the-shivam-gupta Thank you for raising this bug report! Do you want to work on this issue?

**Comment by the-shivam-gupta** [comment]
Ya I would but would take some time as there is already 1 issue that is assigned to me.

**Comment by gopaal24** [comment]
@SaptarshiSarkar12 I would love to work on it as my first open source contribution.

**Comment by SaptarshiSarkar12** [comment]
Thank you for your interest in this issue :smile:!
@gopaal24 Yes, you can work on this issue. Assigning you with the task.

**Comment by gopaal24** [comment]
@SaptarshiSarkar12 While trying to run the website in IDE, it says something like this:
![Screenshot 2023-11-27 173317](https://github.com/SaptarshiSarkar12/Drifty/assets/75197047/e2a6da5b-e359-4032-bf35-cc93f1a6219e)
Should install next or is there any other way around.

I'm sorry if this is basic.
Thank you in advance.

**Comment by the-shivam-gupta** [comment]
@gopaal just get in the folder name "Website" and from there try running the command "npm run dev"

**Comment by SaptarshiSarkar12** [comment]
@gopaal24 Please run `npm ci` to install the dependencies and then run `npm run dev`. It should work.

**Comment by the-shivam-gupta** [comment]
Assign me this issue too I can work on both now. @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta Okay. But let's wait for his (@gopaal24) reply. Till then, @the-shivam-gupta you can work on #282 :grin:.

**Comment by the-shivam-gupta** [comment]
Ok

**Comment by gopaal24** [comment]
Hey, @SaptarshiSarkar12 i'm sorry for stalling a bit too long, i was a bit busy with my minor/ major project and now i am having exams 😐, so @the-shivam-gupta can go ahead with the work, i'll unassign my self.
Thank you.

**Comment by SaptarshiSarkar12** [comment]
It's okay.
@the-shivam-gupta I am assigning you with the task.
