### ISSUE TITLE
Getting unsafe warning while downloading .exe file

### ISSUE THREAD

**Issue by BoseSj** [SaptarshiSarkar12/Drifty#37]
# Description
Getting "Unsafe" warning while downloading the Drifty_CLI.exe
![image](https://user-images.githubusercontent.com/58129377/193469740-65699ccb-e1c2-42c8-b9c1-83dd96f152a5.png)

**OS**: Windows
**Browser**: MS Edge

**Comment by BoseSj** [comment]
It's not really an issue, as one can see the reason for it's occurrence is well provided
![image](https://user-images.githubusercontent.com/58129377/193469912-eb604b4f-661f-43b6-bb6f-17765afc40a8.png)

**Comment by SaptarshiSarkar12** [comment]
Do you want to work on this issue? @BoseSj

**Comment by BoseSj** [comment]
Yeah! Why not, I would love to.

**Comment by SaptarshiSarkar12** [comment]
Ok @BoseSj .

**Comment by SaptarshiSarkar12** [comment]
> It's not really an issue, as one can see the reason for it's occurrence is well provided
> 
> ![image](https://user-images.githubusercontent.com/58129377/193469912-eb604b4f-661f-43b6-bb6f-17765afc40a8.png)

This occurs because the jar file from which I jave created this .exe file needs to be signed. I have done that too, but, it is still not fixing. Probably because the signing certificate is self-signed. So, improving documentation is the only way to fix it as of now.

**Comment by BoseSj** [comment]
Yes. Talking about that. Also user could report it to be safe, and as as owner you can too...

![image](https://user-images.githubusercontent.com/58129377/193470471-5fda7ace-bb2e-4193-914e-067ec0eae64e.png)

**Comment by SaptarshiSarkar12** [comment]
Ok, please send the link

**Comment by BoseSj** [comment]
- Try to download it.

![image](https://user-images.githubusercontent.com/58129377/193470882-ececa3eb-5f47-4bc6-b850-39e916516162.png)

- Tap on the three dots > then on "Keep"

![image](https://user-images.githubusercontent.com/58129377/193470909-ea832116-45d2-4b53-81d8-2f39579a7311.png)

- Tap on "Show More"

![image](https://user-images.githubusercontent.com/58129377/193470921-de45f65c-cc98-42d0-ba7e-9aa3f4c0d2ee.png)

- Tap on "Report this app as Safe"

![image](https://user-images.githubusercontent.com/58129377/193470931-ff07b342-3168-4320-b6b6-09c0ce6eaef3.png)

VOILA!

**Comment by SaptarshiSarkar12** [comment]
Ok shall do it. Thanks for that

**Comment by BoseSj** [comment]
Or you can directly go to [Submit a file for malware analysis](https://www.microsoft.com/en-us/wdsi/filesubmission/). And submit it for analysis.

**Comment by SaptarshiSarkar12** [comment]
> * Try to download it.
> 
> ![image](https://user-images.githubusercontent.com/58129377/193470882-ececa3eb-5f47-4bc6-b850-39e916516162.png)
> 
> * Tap on the three dots > then on "Keep"
> 
> ![image](https://user-images.githubusercontent.com/58129377/193470909-ea832116-45d2-4b53-81d8-2f39579a7311.png)
> 
> * Tap on "Show More"
> 
> ![image](https://user-images.githubusercontent.com/58129377/193470921-de45f65c-cc98-42d0-ba7e-9aa3f4c0d2ee.png)
> 
> * Tap on "Report this app as Safe"
> 
> ![image](https://user-images.githubusercontent.com/58129377/193470931-ff07b342-3168-4320-b6b6-09c0ce6eaef3.png)
> 
> VOILA!

Also, 
# EVERYONE (Contributors + Users)
Should report this application as safe. It would be a great help.

**Comment by BoseSj** [comment]
Should I add this(the steps) directly in the README. So it would be easier for everyone to giving the feedback, and also all of it will be less confusing for them.

**Comment by SaptarshiSarkar12** [comment]
> Should I add this(the steps) directly in the README. So it would be easier for everyone to giving the feedback, and also all of it will be less confusing for them.

Yes @BoseSj

**Comment by BoseSj** [comment]
Ok creating a PR.

**Comment by BoseSj** [comment]
What should I name the section? For example, "Seeing warning while downloading", "Facing problem while downloading" etc.

**Comment by SaptarshiSarkar12** [comment]
> What should I name the section? For example, "Seeing warning while downloading", "Facing problem while downloading" etc.

@BoseSj i have checked your PR and the names of the sections seem right to me. As this problem has been fixed, I am closing this issue.

**Comment by BoseSj** [comment]
Cool 😄! Can you please add `hacktoberfest-accepted` label to the PR? It'd b nice❤️

**Comment by SaptarshiSarkar12** [comment]
> Cool 😄! Can you please add `hacktoberfest-accepted` label to the PR? It'd b nice❤️

Oh, yeah, adding that.
