### ISSUE TITLE
[FEATURE] Add a CLS function on Java using CMD

### ISSUE THREAD

**Issue by Ublinix** [SaptarshiSarkar12/Drifty#39]
**Description**
In the else if statement adding a cls to clear screen on command line

**Comment by SaptarshiSarkar12** [comment]
Great Idea @Ublinix . If anyone wants to work on this issue, please comment below. I would assign you with the task.

**Comment by Fonta22** [comment]
I'd like to work on this!

**Comment by SaptarshiSarkar12** [comment]
ok assigning @Fonta22 . Please link this issue to your PR.

**Comment by Fonta22** [comment]
@SaptarshiSarkar12 could you explain a little bit more in what would the issue consist? I don't really understand where/when the screen should be cleared.

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 could you explain a little bit more in what would the issue consist? I don't really understand where/when the screen should be cleared.

When a single file has been downloaded and the user wants to download another file, the screen containing the details of the previous download should be cleared.

**Comment by Fonta22** [comment]
Okay, thanks!
