### ISSUE TITLE
[FEATURE] Making a gui version of Drifty

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#4]
**Is your feature request related to a problem? Please describe.**
It's not always loved by users to use console applications, rather they find much interest in using GUI (Graphical User Interface) version of any application.

**Describe the solution you'd like**
We nees to build a GUI version of the application. We can use JavaFX or swing for that purpose.

**Additional context**
Contributors who want to take over this issue should at first comment below and then, I would assign them with the task. Multiple assignes can be there.

**Comment by devilkiller-ag** [comment]
Hey can I take this up?

**Comment by SaptarshiSarkar12** [comment]
Yes @devilkiller-ag . But, please ensure that you link this issue to your Pull Request.

**Comment by SaptarshiSarkar12** [comment]
@devilkiller-ag how much is the work done?

**Comment by SaptarshiSarkar12** [comment]
> @devilkiller-ag how much is the work done?

@devilkiller-ag Please provide some updates about your work.

**Comment by m9m** [comment]
Hello, I would also like to be assigned. The scope of what I would do is a basic JavaFX GUI that can be expanded on later.

**Comment by SaptarshiSarkar12** [comment]
Ok  as @devilkiller-ag is not responding,  i am assigning this task to @m9m . If @devilkiller-ag wants to modify the GUI that will be made by @m9m , then you may open another issue and a PR for that.

**Comment by redet-G** [comment]
@m9m Can you give us an update on your progress?

**Comment by SaptarshiSarkar12** [comment]
> @m9m Can you give us an update on your progress?

@redet-G About half of the work has been done.
@m9m has the window layed out and the main elements. They are not connected though.

**Comment by SaptarshiSarkar12** [comment]
> > @m9m Can you give us an update on your progress?
> 
> The GUI is being done in JavaFX. I have most of the styling done. Just need to connect to current functions to the GUI.

@m9m Is is completed?

**Comment by redet-G** [comment]
@m9m Let's put what you have already worked on into a new branch. This way, it is easier to move things faster. 
@SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
> > > @m9m Can you give us an update on your progress?
> > 
> > 
> > The GUI is being done in JavaFX. I have most of the styling done. Just need to connect to current functions to the GUI.
> 
> @m9m Is is completed?

@m9m Please respond.

**Comment by SaptarshiSarkar12** [comment]
@m9m Please respond

**Comment by FDelporte** [comment]
After a quick look into the sources of this project, it's clear that it's not ready to extend with an "extra" UI next to the CLI.  That's probably also why the previous attempts were not successful, see the comments above this one...

Rework is needed to have both a CLI and UI build. In my opinion these initial steps need to be done, before a (JavaFX) UI can be added in a logical and maintainable way:

. Make this a multi-project Maven project
. First sub project: the "backend" code handling the download 
. Second sub project: the existing CLI tool that uses the backend

This way, adding a JavaFX UI in a next step, would be a lot easier. It would be a third sub project, that can offer the same functions as the CLI project, but with a UI, using the same "backend" code.

**Comment by SaptarshiSarkar12** [comment]
Ok @FDelporte . That's a huge task. Can you help me with that? I would be glad for that.

**Comment by SaptarshiSarkar12** [comment]
I am working on the GUI part of the application in the **Drifty-GUI** branch (https://github.com/SaptarshiSarkar12/Drifty/tree/Drifty-GUI). If anyone wants to contribute to the GUI or wants to re-structure the project, can contribute to that branch which will be later merged with the **master** branch (https://github.com/SaptarshiSarkar12/Drifty/tree/master) after the GUI development has been completed.
