### ISSUE TITLE
Update Dockerfile to use environment variables for Maven and GraalVM versions

### ISSUE THREAD

**Issue by Surya-KN** [SaptarshiSarkar12/Drifty#401]
### Description

The versions of Maven and GraalVM in DockerFile are hardcoded. This approach is not flexible and requires manual updates in the Dockerfile each time we want to change the version of Maven or GraalVM. This change will improve the maintainability and flexibility of our Docker setup. It will make it easier to test our application with different versions of Maven and GraalVM, and will simplify the process of updating these tools in the future.

**Comment by SaptarshiSarkar12** [comment]
@Surya-KN Thank you for opening the issue! Good point :+1: 
Would you like to work on this?
