### ISSUE TITLE
[FEATURE]  JS Modification

### ISSUE THREAD

**Issue by akshatjainei** [SaptarshiSarkar12/Drifty#41]
### Describe the solution you'd like.

- Adding Downloader function for Windows and other 
- Redirection for More Info
- Improving Scroll Behavior 

### Application Version

v1.1.0

**Comment by SaptarshiSarkar12** [comment]
ok @akshatjainei , assigning you. Please link this issue to your PR.

**Comment by SaptarshiSarkar12** [comment]
@akshatjainei Is this issue solved?

**Comment by akshatjainei** [comment]
@SaptarshiSarkar12 whatever I was supposed to add , has already been done

**Comment by SaptarshiSarkar12** [comment]
Ok @akshatjainei . If you want to add anything new or want to change any part, you may open an issue and a PR for that.
