### ISSUE TITLE
[FEATURE] Command Line URL Queue

### ISSUE THREAD

**Issue by EasyG0ing1** [SaptarshiSarkar12/Drifty#410]
### Is your feature request related to a problem? Please describe.

No problem is being addressed, this is an enhancement request.

### Describe the solution you'd like.

It might be convenient for some, if the command line side of Drifty could be used as a quick way of adding links into a download queue. For example, if I'm using a web browser, and I come across a link that I want to download, I could just drop into Terminal and type:

```Bash
drifty https://somesite.com/some/link/to/download
```
And Drifty might just respond with something like `Added` and then just exit out. But what Drifty actually did was maybe keep a text file inside the data folder where it accumulates the list of URLs that a user adds via the command line.

Then a user could see which URLs are in the list by passing in an argument which could be:
```Bash
drifty list
drifty queue
```
Or even some other word ... Drifty could even assign line numbers to the list so that a person could remove a URL from the list.

So lets say that I add some URLs to the list:
```Bash
drifty https://www.instagram.com/reel/C1L3vk7owF6/?igsh=YTI4YzE2YTYwMA%3D%3D
drifty https://www.instagram.com/reel/C1xET1sOmeJ/?igsh=YTI4YzE2YTYwMA%3D%3D
drifty https://www.instagram.com/reel/C04_FtZS40L/?igsh=YTI4YzE2YTYwMA%3D%3D
```

The URLs get stored into the file. Then I want to see the list so I do this:
```Bash
drifty list

1    - https://www.instagram.com/reel/C1L3vk7owF6/?igsh=YTI4YzE2YTYwMA%3D%3D
2    - https://www.instagram.com/reel/C1xET1sOmeJ/?igsh=YTI4YzE2YTYwMA%3D%3D
3    - https://www.instagram.com/reel/C04_FtZS40L/?igsh=YTI4YzE2YTYwMA%3D%3D
```

But then I want to remove item 2, so I do this:
```Bash
drifty remove 2
```
Drifty responds with
```Bash
Removed URL from list:
     https://www.instagram.com/reel/C1xET1sOmeJ/?igsh=YTI4YzE2YTYwMA%3D%3D
```

Then, when I'm ready to download the list, I just type:
```Bash
drifty get
```
And Drifty then downloads the list to the last download location I used or maybe it prompts for the download folder while showing that last location as the default if the user just hits enter etc.

### Additional information

I could write this of course, but I've got other things going right now so I think if someone can get started on this right away, then it might be a good opportunity for someone to contribute to the project. I'm more than happy to pass this on to someone who might be interested in writing it.

**Comment by SaptarshiSarkar12** [comment]
Thank you for opening this issue @EasyG0ing1! Great feature to implement :+1:.
If anyone wants to work on this issue, please comment below.

**Comment by Femi-lawal** [comment]
@SaptarshiSarkar12 Please can I work on this?

**Comment by SaptarshiSarkar12** [comment]
Thank you @Femi-lawal for your interest in this issue!
Yes, you can work on this issue.
