### ISSUE TITLE
[FEATURE]  Improve the Website UI - Responsive

### ISSUE THREAD

**Issue by Pargat-Dhanjal** [SaptarshiSarkar12/Drifty#43]
### Is your feature request related to a problem? Please describe.

I would like to work on the entire Website UI and improve it as you can see that there are many things which don't work on the website as well as the UI design is not upto the mark. The Website is not resposive as well as there are many responsive bugs.

### Describe the solution you'd like.

I would like to work on the entire website part as a sole developer to improve the application and provide a better user experince for the application. 

### Application Version

v1.1.0

### Screenshots

<img width="498" alt="Screenshot 2022-10-04 at 2 59 02 AM" src="https://user-images.githubusercontent.com/54456304/193687012-be449f07-7297-4ac2-8f84-e7f2eb32cd72.png">
<img width="497" alt="Screenshot 2022-10-04 at 2 58 54 AM" src="https://user-images.githubusercontent.com/54456304/193687022-2b6e15b6-e767-4ca7-86d9-bd716de8916c.png">
<img width="1450" alt="Screenshot 2022-10-04 at 2 57 13 AM" src="https://user-images.githubusercontent.com/54456304/193687030-13717d29-6006-4dae-9c46-669f5286b74d.png">

### Additional information

Would gladly contribute to this website as a part of hacktober fest and would love to contribute my share to open source applications.

**Comment by SaptarshiSarkar12** [comment]
@Pargat-Dhanjal please wait till @Shashwat0227 open his PR as he is going to complete the basics of the website by today.

**Comment by anuragh2002** [comment]
Hey @Pargat-Dhanjal @SaptarshiSarkar12 is this issue still open? Can you please assign it to me?

**Comment by Pargat-Dhanjal** [comment]
@anuragh2002 I am asking himto assign me the issue. Can you please look up a new one?

**Comment by SaptarshiSarkar12** [comment]
> Hey @Pargat-Dhanjal @SaptarshiSarkar12 is this issue still open? Can you please assign it to me?

After @Pargat-Dhanjal has completed this work, @anuragh2002, you may modify this if you want, through another issue and a PR.

**Comment by SaptarshiSarkar12** [comment]
@Pargat-Dhanjal The website has changed a lot. So, please have a check, pull the latest changes and then open your PR.

**Comment by Pargat-Dhanjal** [comment]
@SaptarshiSarkar12 sure
