### ISSUE TITLE
[BUG] Fix the navbar animation

### ISSUE THREAD

**Issue by Waxer59** [SaptarshiSarkar12/Drifty#44]
### Description

# Fix
* Navbar animation: the current navbar animation changes very abruptly #
* Change the cursor of the navbar elements to a pointer cursor

### Application Version

v1.1.0

**Comment by SaptarshiSarkar12** [comment]
Thanks @Waxer59 for this issue, do you want to work on this issue?
Or, if anyone wants to work on it, can comment below and I shall assign you with the task.

**Comment by SaptarshiSarkar12** [comment]
@Waxer59 Please leave a star if you liked my project.
