### ISSUE TITLE
[FEATURE] Want to change the font color for the first section 

### ISSUE THREAD

**Issue by anshulsoni4** [SaptarshiSarkar12/Drifty#47]
### Is your feature request related to a problem? Please describe.

The current color of the section is white, it is not matching with the background color. So we can change it to a darker shade.

### Describe the solution you'd like.

I will change the font color to black or a darker shade of any color so that it is visible enough (when it is not in the dark mode)

### Application Version

v1.1.0

### Screenshots

![image](https://user-images.githubusercontent.com/74638335/193739907-02dfe438-62e3-4cd5-976b-63375c183452.png)

**Comment by SaptarshiSarkar12** [comment]
Great! assigning you. Please link this issue to your PR.

**Comment by aryan-upa** [comment]
Hey assign me the task.

**Comment by SaptarshiSarkar12** [comment]
@anshulsoni4 is already assigned, so, @aryan-upa you may modify the changes through another PR and issues after it is merged.

**Comment by aryan-upa** [comment]
I am working on the website, but it is more of a revamp. I am going to make it, and show it to all of you.

**Comment by SaptarshiSarkar12** [comment]
@aryan-upa Okay, you may do so through another issue and PR.

**Comment by anshulsoni4** [comment]
@SaptarshiSarkar12 there are so many errors in this section of code 
am closing this issue as it will consume so much time debugging it

**Comment by SaptarshiSarkar12** [comment]
Ok @anshulsoni4

**Comment by SaptarshiSarkar12** [comment]
Feel free to open a new issue and PR if you want to modify any part of this project. You may also file a bug report if you discover any.

**Comment by anshulsoni4** [comment]
> Feel free to open a new issue and PR if you want to modify any part of this project. You may also file a bug report if you discover any.

sure sir 
Thanks a lot @SaptarshiSarkar12
