### ISSUE TITLE
[FEATURE] Add heading to contact us section 

### ISSUE THREAD

**Issue by anshulsoni4** [SaptarshiSarkar12/Drifty#48]
### Is your feature request related to a problem? Please describe.

There is no heading to the contact us section, we can add it.

### Describe the solution you'd like.

I will add heading = Contact Us, as it is looking like a footer but it is a contact us section

### Application Version

v1.1.0

**Comment by SaptarshiSarkar12** [comment]
Great! assigning you. Please link this issue to your PR.
