### ISSUE TITLE
[DOCS]  Edit CONTRIBUTING.md

### ISSUE THREAD

**Issue by anshulsoni4** [SaptarshiSarkar12/Drifty#49]
### How would you improve the documentation? Please describe.

edit the contributing.md file which is important for a project, as it tells us the Prerequisite, and steps to contribute to any project.

**Comment by SaptarshiSarkar12** [comment]
@anshulsoni4 It's already present. Check here : https://github.com/SaptarshiSarkar12/Drifty/blob/master/CONTRIBUTING.md

**Comment by anshulsoni4** [comment]
Alright @SaptarshiSarkar12

**Comment by anshulsoni4** [comment]
@SaptarshiSarkar12 can I enhance it more ?

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 can I enhance it more ?

Yes, you can do so.

**Comment by anshulsoni4** [comment]
@SaptarshiSarkar12 thanks a lot

**Comment by SaptarshiSarkar12** [comment]
@anshulsoni4 Welcome

**Comment by SaptarshiSarkar12** [comment]
How much work has been done @anshulsoni4 ?

**Comment by anshulsoni4** [comment]
umm, i have merged 4 PRs so ...

**Comment by SaptarshiSarkar12** [comment]
> umm, i have merged 4 PRs so ...

@anshulsoni4 Still, you may contribute as an open-source contribution.
