### ISSUE TITLE
[FEATURE] Add progress bar for Drifty

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#5]
**Is your feature request related to a problem? Please describe.**
The user gets impatient when a large file is being downloaded but the application doesn't display how much percent of the file has been downloaded / left . They simply think that the application has become unresponsive and creates a negative impact on the user.

**Describe the solution you'd like**
A progress bar which will show how much percentage of the file has been downloaded / left.

**Additional context**
Contributors who want to take over this issue should at first comment below then I will assign them with the task. Ensure that you will link this issue to your Pull Request. Multiple assignes can be there. Just leave a comment below if you are interested.

**Comment by m9m** [comment]
Hello! I would like to be assigned.
