### ISSUE TITLE
[FEATURE] Navbar scroll

### ISSUE THREAD

**Issue by Waxer59** [SaptarshiSarkar12/Drifty#58]
### Is your feature request related to a problem? Please describe.

When you click on a link in the navbar it makes a very abrupt jump to the selected element,

### Describe the solution you'd like.

I think it would look better if instead it made a vertical scroll until you reach that element.
If you agree with my proposal I can implement these changes to the project

### Application Version

v1.1.0

**Comment by SaptarshiSarkar12** [comment]
@Waxer59 Do you want to work on this issue?

**Comment by Waxer59** [comment]
Sure!

**Comment by SaptarshiSarkar12** [comment]
Great ! @Waxer59 . Please link this to your PR.

**Comment by psb27** [comment]
If no body is working on this issue please assign this to me.

**Comment by SaptarshiSarkar12** [comment]
@Waxer59 is working on this. 
@psb27 If you want you may modify that after his PR is merged, or you may open another issue for feature request or bug report etc.
