### ISSUE TITLE
[OTHER] Remaster the hero section and the nav bar of the website

### ISSUE THREAD

**Issue by Anurag-Bharati** [SaptarshiSarkar12/Drifty#59]
### Description

The website's current hero section and nav bar are good, but I want to up it.
I would like to redesign both.

### Application Version

v1.1.0

### Additional information

I also am planning to add animations and illustrations to the hero section.

**Comment by SaptarshiSarkar12** [comment]
Great @Anurag-Bharati! Please link this to your PR.
