### ISSUE TITLE
[FEATURE] Adding support for multiple download URLs as input

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#6]
**Is your feature request related to a problem? Please describe.**
The users in most cases have to download more than one file, so, in the [current version of Drifty](https://github.com/SaptarshiSarkar12/Drifty/releases/tag/v1.0.0), the user can enter maximum one download link and after the file has been downloaded, the application closes.

**Describe the solution you'd like**
The solution to this problem can be adding arrays to store multiple URLs, respective filenames and respective directories as input. Or, a while loop can also be introduced to run till the user enters `stop` or the number of files the user wants to download has exceeded.

**Additional context**
Contributors who want to take over this issue should at first comment below then I will assign them with the task. Multiple assignes can be there.

**Comment by akshatjainei** [comment]
I would like to fix this issue   , can you assign me this task

**Comment by SaptarshiSarkar12** [comment]
Yes @akshatjainei . Please make sure that you will link this issue to your PR.

**Comment by thexahmed00** [comment]
I want to take this issue and I am very new to opensource

**Comment by SaptarshiSarkar12** [comment]
This work is about to complete. So, @thexahmed00 you may open other issues and contribute to those.
