### ISSUE TITLE
[BUG] Missing Dark Mode for "Manage Directories" window

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#604]
### Describe the bug

The "Manage Directories" window in Drifty GUI, does not have dark mode support till now.
Moreover, when the **Help** window (the Drifty GUI's **Information** window) is opened twice without the first window being closed, a new window opens. The former window becomes completely blank, and the second window shows up with the expected content.

#### For first issue of missing Dark Mode in **`Manage Directories`** window
1. Open **Drifty GUI**
2. Right click anywhere near the **`Directory:`** label. A small context menu appears. 
    ![directory context menu](https://github.com/user-attachments/assets/f312ee7d-1b46-4bbd-83f7-c71757927340)
3. Click on **Manage Directories**.
4. A window opens up in light theme as shown below :point_down:
    ![image](https://github.com/user-attachments/assets/29adf66f-e006-4209-a004-c62f39ade973)

#### For second issue of the **`Help window`** getting opened twice
1. Open **Drifty GUI**
2. Right click anywhere in the right side (in the **download queue** area) of the application. A context menu appears like this:
    ![image](https://github.com/user-attachments/assets/491b5b61-a4af-4d48-ad03-b4a0808f61b1)
3. Click on **Information**. A **Help window** appears.
    ![image](https://github.com/user-attachments/assets/74587746-b765-4afd-9c2b-3bc008624b2c)
4. Without closing **the current Help window**, again follow the 2nd and 3rd step to open a new instance of the **Help window**. You can see that the first window becomes completely blank.
    ![image](https://github.com/user-attachments/assets/4fea3fd8-a28c-452c-92ea-4c7a7ea28809)

### Expected Behavior

The **Manage Directories** window must show dark theme in sync with the global theme applied. Moreover, a new Help window must not open when already one window is active.

### Operating System / Environment

Linux 🐧

### Screenshots

![Missing dark mode in Manage Directories](https://github.com/user-attachments/assets/0e8feba4-4c39-4c82-845c-6a0a47d165f3)
![Duplicate Help window](https://github.com/user-attachments/assets/722b7d03-8f1d-4a53-94c0-9bd055e39663)

### Additional information

If anyone wants to work on this issue, please comment below.

**Comment by ziad-ashraf7** [comment]
hello mr. @SaptarshiSarkar12 , 
i would like to work on this issue : )

**Comment by SaptarshiSarkar12** [comment]
@ziad-ashraf7 Hello Ziad :wave:!
Thank you for your interest in working on this issue. I am assigning this issue to you.
