### ISSUE TITLE
[FEATURE] Youtube Playlist Download feature in Drifty CLI

### ISSUE THREAD

**Issue by Tarunkumarkanakam** [SaptarshiSarkar12/Drifty#631]
### Is your feature request related to a problem? Please describe.

When attempting to download a YouTube playlist using Drifty CLI, the tool fails to handle playlist URLs correctly. Although the link validation passes, the CLI is designed to extract a single video ID (from URLs like `?v=videoID`) but fails when provided with a playlist URL (which uses the list parameter for the playlist ID). The error message displayed is: "YouTube video ID not found in the link," indicating that the CLI does not currently support playlist downloads.

This can be reproduced as follows

1. Run Drifty CLI.
2. Select "Single File Download."
3. Provide a YouTube playlist URL (e.g., https://www.youtube.com/playlist?list=PLMC9KNkIncKtPzgY-5rmhvj7fax8fdxoj).
4. The CLI returns: "YouTube video ID not found in the link."

### Describe the solution you'd like.

1. Update Drifty CLI to properly detect playlist URLs by looking for the list= parameter in Drifty_CLI.java
2. Implement functionality to parse the playlist and download all videos in the playlist which is available in Drifty_GUI.java.
3. Provide better error handling and messaging if a playlist URL is detected but can't be processed.
4. Add an option for users to download entire playlists or select specific videos from the playlist for download would be a cool feature.

This can be referenced to issue #601 

### Screenshots

<img width="1421" alt="image" src="https://github.com/user-attachments/assets/2e4a6d4e-63ae-424c-b5ee-08415e57484c">

### Do you want to work on this issue?

No

**Comment by SaptarshiSarkar12** [comment]
@Tarunkumarkanakam Thank you for creating this feature request.
If anyone wants to work on this issue, please comment below.
