### ISSUE TITLE
[FEATURE] Want to enhance the contact us page for the websire

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [SaptarshiSarkar12/Drifty#663]
### Is your feature request related to a problem? Please describe.

I want to enhance the contact us page for the website 
I will improve the designing of the web page 

### Describe the solution you'd like.

I will make the contact page more attractive 

### Screenshots

![image](https://github.com/user-attachments/assets/0352edbf-cd7f-4e9e-9f84-09c7ae440ad2)

I WILL CONVERT IT TO THIS 

![image](https://github.com/user-attachments/assets/b77a878f-9aed-4f0d-8370-a982a17d3b31)

### Do you want to work on this issue?

Yes

**Comment by SaptarshiSarkar12** [comment]
Awesome enhancement 👏.
I loved the new UI.
Thank you for the issue. 
@Ayushmaanagarwal1211 Assigning you with the task.
