### ISSUE TITLE
[BUG] Nav bar is not sticky on scrolling in mobile phones

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#667]
### Describe the bug

The nav bar neither remain fixed nor gets closed when the mobile phone user starts scrolling down. Check the Screen recording attached.

### Steps To Reproduce

1. Go to the website in any phone browser.
2. Click on the three bar at the top right corner to open the nav bar. 
3. Once the nav bar is open, try scrolling down.
4. You can see that the nav bar also moves up as you scroll down.

### Expected Behavior

The nav bar should either get hidden/closed or remain fixed and must not move up as the user scrolls down.

### Operating System

Other

### Browser

Microsoft Edge, Google Chrome

### Screenshots

https://github.com/user-attachments/assets/cb3e9d2b-79a4-496f-9ad3-4a3a22d1abc0

### Additional information

If anyone wants to work on this issue, please feel free to comment below.

### Do you want to work on this issue?

No

**Comment by drippypop** [comment]
Hi! I'd like to fix this. Can you assign this issue to me?

**Comment by SaptarshiSarkar12** [comment]
Hi @drippypop 👋!
Thank you for your interest in the issue.
Yeah, you can work on this issue. Assigning this task to you 😁.

**Comment by drippypop** [comment]
Hi @SaptarshiSarkar12,

Just fixed the issue! Thanks so much for assigning me this, it was pretty nice to work on and easy to fix! 😄

**Comment by SaptarshiSarkar12** [comment]
@drippypop Thank you for fixing the issue with great speed 🙂. I have reviewed your PR. Please make the change and let me know.
Glad that you have loved working on this issue 😃.
