### ISSUE TITLE
[BUG] Hide pre-releases if latest version released succeeds the pre-release version

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#670]
### Describe the bug

Currently, the Website shows the pre-release version (`v2.1.0-rc.1`) even after `v2.1.0` has been released.

### Steps To Reproduce

1. Go to the official website. 
2. Click on **Download**.
3. You can see that the latest version is `v2.1.0` but the Release Candidate release of `v2.1.0-rc.1` is still shown.

### Expected Behavior

Any pre-release must not be shown if there is a stable release already made after the pre-release had been released. 
Here are some examples 👇
- stable: `v2.0.0` , pre-release: `v2.1.0-beta.1` => pre-release shown ✅ 
- stable: `v2.1.0` , pre-release: `v2.1.0-beta.1` => pre-release shown ❌ 

### Operating System

Windows 🪟, MacOS 🍏, Linux 🐧, Other

### Browser

Microsoft Edge, Google Chrome, Safari, Brave, Other

### Screenshots

https://github.com/user-attachments/assets/5cb69e06-5113-4074-b5c4-9b4db8e29d06

### Additional information

If anyone wants to work on this issue, please comment down below.

### Do you want to work on this issue?

No

**Comment by aaronrojas32** [comment]
Hey, I would like to work on it, can u asing me this issue?

**Comment by SaptarshiSarkar12** [comment]
@aaronrojas32 Hi Aaron 👋!
Thank you for your interest in the issue 😁!
Assigning this task to you 😃.
