### ISSUE TITLE
[BUG] The nav bar does not close if the selected nav item is already loaded

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#673]
### Describe the bug

If we are on a page (say, download page) and we click on nav bar, then on the same page's nav item (here, `download`), the nav bar neither closes nor reloads the page. 

### Steps To Reproduce

1. Go to the official website on any phone.
2. Click on any nav item (download, contact us, or about) 
3. After that page is loaded, re-open the nav bar and click on that same nav item once again.
4. You can see that neither the nav bar closes nor does the page reload.

### Expected Behavior

The nav bar must either close or reload the page. Closing the nav bar is preferable to reduce network usage.

### Operating System

Other

### Browser

Microsoft Edge, Google Chrome, Safari, Brave, Other

### Screenshots

https://github.com/user-attachments/assets/400a768c-e982-41ff-b78e-b70b1016a629

### Additional information

If anyone wants to contribute to this issue, please comment down below.

### Do you want to work on this issue?

No

**Comment by drippypop** [comment]
Hello again! Mind if I work on this?

**Comment by SaptarshiSarkar12** [comment]
@drippypop No issue 😄. You can work on this. Thank you for your interest 😀.
Assigning this task to you 😁.
