### ISSUE TITLE
feat: add buttons for navbar items

### ISSUE THREAD

**Issue by yalsik86** [SaptarshiSarkar12/Drifty#682]
### Is your feature request related to a problem? Please describe.

nav bar options of Home, About, Contact and Download looks odd and bland

### Describe the solution you'd like.

I'll be adding buttons with hover effect to make it more aesthetically pleasing.

@SaptarshiSarkar12 please assign me this issue and label as hacktoberfest.

### Screenshots

![Screenshot 2024-10-11 005855](https://github.com/user-attachments/assets/8f38a095-8153-4a67-bcca-b9df30cf445f)

### Do you want to work on this issue?

Yes

**Comment by SaptarshiSarkar12** [comment]
Thank you for this enhancement issue 😃.
@yalsik86 Assigning this task to you 😁.
