### ISSUE TITLE
[FEATURE] Make a website for the documentation of Drifty

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#7]
**Is your feature request related to a problem? Please describe.**
People don't always like to read Documentation from Readme. They want some website which will have a visually appealing look and all the sufficient details of using this application as well as support URLs.

**Describe the solution you'd like**
A website using html and css containing the documentation present in the README and a navbar should also be present. The support URLs (GitHub issues, My email address, my twitter account for DMs) should be present at the footer.

**Additional context**
Contributors who want to take over this issue should at first comment below then I will assign them with the task. Multiple assignes can be there. Feel free to contact me for any questions.

**Comment by Shashwat0227** [comment]
hey i can make this

**Comment by Shashwat0227** [comment]
i can make site , footers , nav bar and also add dark mode feature and all

**Comment by SaptarshiSarkar12** [comment]
Ok @Shashwat0227 . Assigning you with the task. Make sure that you link this issue to your PR.

**Comment by Shashwat0227** [comment]
thankyou

**Comment by avezqureshi14** [comment]
Hello Sir, I can add all the features which are present in your requirements  and along with this I will make your site using REACT JS which will be scalable if you want to add any more future complex functionality , You can checkout my portfolio for my work regarding REACT JS [https://avezqureshi.netlify.app/](url)

**Comment by SaptarshiSarkar12** [comment]
@avezqureshi14 You will make the website using react containing the documentation in readme and @Shashwat0227 would modify it with some more items. 
Ensure that you both will link this issue to your PRs which will help in tracking the progress of this application.

**Comment by SaptarshiSarkar12** [comment]
@avezqureshi14 Can you make the website using react **by 4th October** ?

**Comment by SaptarshiSarkar12** [comment]
> @avezqureshi14 Can you make the website using react **by 4th October** ?

@avezqureshi14 Please reply

**Comment by SaptarshiSarkar12** [comment]
As @avezqureshi14 is not replying and @Shashwat0227 is interested to make the website using html, css etc., so, i am assigning him this task. @Shashwat0227 Please link this issue with your PR. 

@avezqureshi14 if you want you may open another PR to modify the website by including React.

**Comment by Shashwat0227** [comment]
made the site check em once

**Comment by SaptarshiSarkar12** [comment]
ok @Shashwat0227 .

**Comment by Shashwat0227** [comment]
hey can you accept it so that it displays on my hacktoberfest site , and after that i can proceed further with adding footers and other modifications

**Comment by SaptarshiSarkar12** [comment]
ok @Shashwat0227

**Comment by SaptarshiSarkar12** [comment]
@avezqureshi14 I am closing this issue, but, if you want, you may modify the website through another issue and PR.
