### ISSUE TITLE
[OTHER] Rework on the contribute section. 

### ISSUE THREAD

**Issue by Anurag-Bharati** [SaptarshiSarkar12/Drifty#71]
### Description

The contribute section seems kinda empty at the moment. I would love to add more content and improve its appearance.

### Application Version

v1.1.0

**Comment by SaptarshiSarkar12** [comment]
> ### Description
> The contribute section seems kinda empty at the moment. I would love to add more content and improve its appearance.
> 
> ### Application Version
> v1.1.0
> 
> ### Additional information
> _No response_

@Anurag-Bharati For the website?

**Comment by Anurag-Bharati** [comment]
yes

**Comment by SaptarshiSarkar12** [comment]
Please link this issue to your PR
