### ISSUE TITLE
[BUG] Some items appear smaller in some mobiles

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#72]
### Describe the bug

The text in buttons in some parts of the website appears very small. It includes the more info, contact us and Download section containing the three buttons.

### Steps To Reproduce

1. Go to [`Drifty's Website`](https://saptarshisarkar12.github.io/Drifty/) in MS Edge.
2. Press <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>I</kbd> or open `DevTools`.
3. Press <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>M</kbd> or Toggle `Device Emulation`.
4. Click on `Dimensions` and select `iPhone SE` or `iPhone 12 Pro` or `Pixel 5` or `Samsung Galaxy S8+`, etc.
5. See the bug as given in the screenshot below.

### Expected Behavior

Texts should have proper size and should be displayed properly.

### Operating System

Other

### Application Version

v1.1.0

### Screenshots

Samsung Galaxy S8+

![saptarshisarkar12 github io_Drifty_(Samsung Galaxy S8+)](https://user-images.githubusercontent.com/105960032/194511262-3c72b47e-b872-41e8-b3d5-6c4f4c7a7468.png)

iPhone SE 

![saptarshisarkar12 github io_Drifty_(iPhone SE)](https://user-images.githubusercontent.com/105960032/194511509-6c0fea9f-c7d8-48f9-92f8-082c18123a5e.png)

### Additional information

If anyone wants to work on this issue, you can comment below, and I would assign you with the task.

**Comment by Akshu-on-github** [comment]
I'd like to work on this please!

**Comment by SaptarshiSarkar12** [comment]
> I'd like to work on this please!

Ok @Akshu-on-github. Assigning you with the task. Please link this issue to your PR.

**Comment by manishgupta416** [comment]
Can you assign to me?

**Comment by SaptarshiSarkar12** [comment]
@Akshu-on-github is already assigned. So, after @Akshu-on-github 's PR is merged, @manishgupta416, you may open another PR to modify those changes. Or, you may open another issue and a PR to make any other changes in any part of the project.

**Comment by SaptarshiSarkar12** [comment]
@Akshu-on-github How much work has been completed?

**Comment by Akshu-on-github** [comment]
@SaptarshiSarkar12 here's a screenshot what I've fixed:
 | Before | After |
|-|-|
| ![image](https://user-images.githubusercontent.com/61582763/194947065-ac9d065b-c857-40a5-9f67-f3cd822c9d35.png) | ![image](https://user-images.githubusercontent.com/61582763/194947127-e5f4cc84-f284-4f83-a92f-c768ad1de6cf.png) |

The bug in the contact us section was pretty much fixed when the number of words was reduced. But the gif in the hero section is something I'm working on right now - I'll create a PR once I figure it out:
![image](https://user-images.githubusercontent.com/61582763/194947968-8c8ca56d-0d35-48e0-9cf6-ddeb9229ee5f.png)

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 here's a screenshot what I've fixed:
> 
> Before	After
> ![image](https://user-images.githubusercontent.com/61582763/194947065-ac9d065b-c857-40a5-9f67-f3cd822c9d35.png)	![image](https://user-images.githubusercontent.com/61582763/194947127-e5f4cc84-f284-4f83-a92f-c768ad1de6cf.png)
> The bug in the contact us section was pretty much fixed when the number of words was reduced. But the gif in the hero section is something I'm working on right now - I'll create a PR once I figure it out: ![image](https://user-images.githubusercontent.com/61582763/194947968-8c8ca56d-0d35-48e0-9cf6-ddeb9229ee5f.png)

Great @Akshu-on-github ! Waiting fo your PR.
