### ISSUE TITLE
[FEATURE] Revamp the website with modern design

### ISSUE THREAD

**Issue by FabrizioJordan** [SaptarshiSarkar12/Drifty#720]
### Is your feature request related to a problem? Please describe.

The website uses bad web practices and looks old and outdated.

### Describe the solution you'd like.

Bad practices: Using grid, padding and margin to separate elements instead of flex.
I replaced the incorrectly used padding and margin with flex and gap. 
PD: the grid is more difficult and not necessary in these cases.

Bug: Main section image animation shows scrollbar on X axis.
Fix: Overflow hidden in container div .

From antique buttons and anchors to modern and clean designs. Borderless, better border radius, more correct size, etc.

Minor changes in Footer. Minor changes in Demo section.

These changes improve consistency across the website.

### Home section:
With 2 buttons in header on hover:
![image](https://github.com/user-attachments/assets/e684dc4b-ad60-4dc1-a39a-a102eed1858d)

### Contribute section:
With 2 buttons in header, 3 contributors avatar and fork button on hover:
![image](https://github.com/user-attachments/assets/86f19cec-0047-49d0-a5c4-3eac549e2925)

### Demo section:
Normal:
![image](https://github.com/user-attachments/assets/21dcdb81-5d04-44c9-aef2-c652c2485558)

Buttons on hover:
![image](https://github.com/user-attachments/assets/94f93014-0f1b-4527-8b0d-6f5c7f6d7eca)

### Footer:
![image](https://github.com/user-attachments/assets/467b14ce-c28a-4d6c-9019-1b0441eabbf8)

### Do you want to work on this issue?

Yes

**Comment by SaptarshiSarkar12** [comment]
@FabrizioJordan Thank you Fabricio for creating the issue :smile:!
I agree with your points and the UI looks good now :clap:. You can work on it. I would assign this issue to you.

> Sorry for my English, I don't speak it very well.

It's okay :upside_down_face:.

> And this is one of my first contributions.

Oh, welcome to Open-Source :heart:!
