### ISSUE TITLE
[FEATURE] ADDING DARKMODE TO THE SITE 

### ISSUE THREAD

**Issue by Shashwat0227** [SaptarshiSarkar12/Drifty#8]
I can add dark mode with a button on the site

**Comment by SaptarshiSarkar12** [comment]
@Shashwat0227 do you want to work on this issue?

**Comment by SaptarshiSarkar12** [comment]
Assigned @Shashwat0227 . Make sure you link this issue to your PR.

**Comment by Anuran12** [comment]
Hi @Shashwat0227 can you please assign it to me?

**Comment by Anshuman047** [comment]
Hey @Shashwat0227 , could I contribute in this issue..?

**Comment by SaptarshiSarkar12** [comment]
As the code is a small, so, @Shashwat0227 wants to do it by himself. 
@Anuran12 @Anshuman047 You may open an issue requesting for a feature and you may contribute to those. I would assign you then.

**Comment by SaptarshiSarkar12** [comment]
@Anuran12 @Anshuman047 You may work on some new issues just started (#16, #15 and #13 )

**Comment by SaptarshiSarkar12** [comment]
Closing this as it is completed (#35).
