### ISSUE TITLE
[FEATURE] I would like to make the website mobile responsive in the hero section

### ISSUE THREAD

**Issue by SujalSamai** [SaptarshiSarkar12/Drifty#80]
### Is your feature request related to a problem? Please describe.

When opening the website from a smartphone or laptop, the hero section seems broken

### Describe the solution you'd like.

I would like to make it responsive using flexbox so that the mobile users don't face any problem while using the website.

### Application Version

v1.1.0

### Screenshots

![image](https://user-images.githubusercontent.com/87236576/194695301-9f78f7ac-272c-42e1-91ce-3df90dfe68a9.png)

**Comment by SaptarshiSarkar12** [comment]
Ok @SujalSamai. Assigning you with the task. Please link this issue to your PR.

**Comment by SaptarshiSarkar12** [comment]
Please fix this one also - 

![image](https://user-images.githubusercontent.com/105960032/194697333-57736558-d4f8-41d6-ad97-ccd6a27e57bb.png)

**Comment by SujalSamai** [comment]
> @SujalSamai Please fix this one also -
> 
> ![image](https://user-images.githubusercontent.com/105960032/194697333-57736558-d4f8-41d6-ad97-ccd6a27e57bb.png)

Sure I'll do

**Comment by SaptarshiSarkar12** [comment]
> > @SujalSamai Please fix this one also -
> > ![image](https://user-images.githubusercontent.com/105960032/194697333-57736558-d4f8-41d6-ad97-ccd6a27e57bb.png)
> 
> Sure I'll do

Thanks, waiting for your Pull Request.
