### ISSUE TITLE
Add Stars And Forks in the footer of the website

### ISSUE THREAD

**Issue by koder-aritra** [SaptarshiSarkar12/Drifty#82]
### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like.

I will add the count of the number of forks and stars of your repository in the footer section of your website.

### Application Version

v1.1.0

### Additional information
If approved please assign this issue to me.

**Comment by SaptarshiSarkar12** [comment]
ok @koder-aritra . Great feature @koder-aritra! Please make a feature to display the avatar of a random contributor to this repo, showing thanks to them for contributing, at the bottom of the website. It will look good perhaps. What do you suggest?

Please link this issue to your PR.

**Comment by SaptarshiSarkar12** [comment]
Please leave a star if you liked this project.

**Comment by koder-aritra** [comment]
Please let me add only the count of the forks and stars of the repo.

**Comment by SaptarshiSarkar12** [comment]
> Please let me add only the count of the forks and stars of the repo.

ok

**Comment by SaptarshiSarkar12** [comment]
@koder-aritra How much work has been done?

**Comment by SaptarshiSarkar12** [comment]
> Please let me add only the count of the forks and stars of the repo.

@koder-aritra How much work has been done?

**Comment by Akshatjaiswal5** [comment]
Hey @SaptarshiSarkar12, I would like to work on this issue, Please assign me.

**Comment by SaptarshiSarkar12** [comment]
> Hey @SaptarshiSarkar12, I would like to work on this issue, Please assign me.

As @koder-aritra is not responding, I am assigning this issue to @Akshatjaiswal5 . If @koder-aritra wants to modify the changes, he may do the same.
