### ISSUE TITLE
Edit Buttons![FEATURE] 

### ISSUE THREAD

**Issue by frypan01** [SaptarshiSarkar12/Drifty#83]
### Is your feature request related to a problem? Please describe.

Button animation have  an  unfinished kind if look ! as if stuck or in loop ,and the on hover animation and change in color does not match with color scheme of the entire website. 

### Describe the solution you'd like.

I would love to add a much smoother on hover animation and better colors to buttons.

### Application Version

v1.1.0

**Comment by bhumika-1-3** [comment]
can u assign me?

**Comment by SaptarshiSarkar12** [comment]
@frypan01 Do you want to work on this issue?  Else I would assign @bhumika-1-3 with the task.

**Comment by frypan01** [comment]
yes !! I would love to

**Comment by SaptarshiSarkar12** [comment]
> yes !! I would love to

Ok @frypan01 . Please link this issue to your PR. 
After @frypan01's PR is reviewed and merged, @bhumika-1-3 , you may modify the chanhes through another PR.

**Comment by SaptarshiSarkar12** [comment]
This issue has been closed due to inactivity in #130
