### ISSUE TITLE
Make a better footer![FEATURE] 

### ISSUE THREAD

**Issue by MashiBan** [SaptarshiSarkar12/Drifty#84]
### Is your feature request related to a problem? Please describe.

The footer looks kind of very basic and unfinished, also the hero section text is simple .

### Describe the solution you'd like.

I would like to change the footer and remove the red color after effect with some matching colors. Change the  position of social  media buttons and edit the font in hero section text.

### Application Version

v1.1.0

**Comment by SaptarshiSarkar12** [comment]
@frypan01 Ok assigning you with the task. Please link this issue to your PR.

**Comment by manishgupta416** [comment]
Can you assign to me?

**Comment by SaptarshiSarkar12** [comment]
> Can you assign to me?

@frypan01 is already assigned. So, after @frypan01's PR is merged, @manishgupta416, you may open another PR to modify those changes.

**Comment by Aditi-1709** [comment]
I guess the one working on it is inactive so can u assign this to me ?

**Comment by SaptarshiSarkar12** [comment]
> I guess the one working on it is inactive so can u assign this to me ?

Yeah sure @Aditi-1709.

**Comment by Aditi-1709** [comment]
Can you exactly specify what changes you expect?

**Comment by SaptarshiSarkar12** [comment]
> Can you exactly specify what changes you expect?

@Aditi-1709 Already @frypan01 has made a PR changing some button transition colours. I shall review that now. If you think you want to bring some good changes to the footer such that it looks visually appealing, you can do so through another PR.

**Comment by SaptarshiSarkar12** [comment]
@Aditi-1709 Are you working on this issue? Else I may close this.

**Comment by Aditi-1709** [comment]
You said the @frypan01 did it so I wasn't working. If it's still available, I can do it .

**Comment by Aditi-1709** [comment]
And yes, it will be better if you specify all your requirements.

**Comment by SaptarshiSarkar12** [comment]
> You said the @frypan01 did it so I wasn't working. If it's still available, I can do it .

Ok @Aditi-1709 , you need to make the footer visually more appealing and beautiful ensuring that it should be responsive. You can change the colour or add glow or colourful shadow to the icons and such other things of your choice to make the footer look beautiful.
You are already assigned so you may start the work. If you face any problem, let me know and I shall try to help you.

**Comment by SaptarshiSarkar12** [comment]
Closing this as inactive.
