### ISSUE TITLE
[FEATURE]  Would add a contact form

### ISSUE THREAD

**Issue by KIET7UKE** [SaptarshiSarkar12/Drifty#87]
### Is your feature request related to a problem? Please describe.

Many "Aalsi" peoples may never click on the email or Twitter buttons for contacting to the admin for a short message.

### Describe the solution you'd like.

I want to add a contact form in the contact section of the website so that visitors can easily get back to the admin.

### Application Version

v1.1.0

**Comment by SaptarshiSarkar12** [comment]
Great idea @KIET7UKE 😄! Do you want to work on this issue?

**Comment by SaptarshiSarkar12** [comment]
Great idea @KIET7UKE 😄!
Assigning you with the task. Please link this issue to your PR .

**Comment by KIET7UKE** [comment]
> Great idea @KIET7UKE 😄!
> Assigning you with the task. Please link this issue to your PR . 

Thanks man, will do it asap.

**Comment by SaptarshiSarkar12** [comment]
> > Great idea @KIET7UKE 😄!
> > Assigning you with the task. Please link this issue to your PR .
> 
> Thanks man, will do it asap.

Welcome 😄 , waiting for your pull request.

**Comment by manishgupta416** [comment]
Can you assign to me?

**Comment by SaptarshiSarkar12** [comment]
@KIET7UKE is already assigned. So, after @KIET7UKE's PR is merged, @manishgupta416, you may open another PR to modify those changes. Or, you may open another issue and a PR to make any other changes in any part of the project.

**Comment by KIET7UKE** [comment]
Hey @SaptarshiSarkar12 I have done the task and made an PR https://github.com/SaptarshiSarkar12/Drifty/pull/92, 
Kidly check this out

**Comment by KIET7UKE** [comment]
Hey @SaptarshiSarkar12 Solved this issue and made a PR https://github.com/SaptarshiSarkar12/Drifty/pull/97
Kidly check this out.

**Comment by SaptarshiSarkar12** [comment]
As @KIET7UKE is busy with his placement interviews and is not able to continue with this, I am closing this issue. This feature is now going to be discussed and processed in #186 .
