### ISSUE TITLE
Edit Nav Bar [FEATURE] 

### ISSUE THREAD

**Issue by MashiBan** [SaptarshiSarkar12/Drifty#88]
### Is your feature request related to a problem? Please describe.

Nav Bar is too dark and blocks the view to the content!

### Describe the solution you'd like.

Edit the Nav Bar with a sleek design to compliment the theme of website.

### Application Version

v1.1.0

**Comment by SaptarshiSarkar12** [comment]
@frypan01 Do you want to work on this issue?

**Comment by manishgupta416** [comment]
Can you assign to me, i want to try this?

**Comment by SaptarshiSarkar12** [comment]
> Can you assign to me, i want to try this?

Sure @manishgupta416 . Please link this issue to your PR.

**Comment by frypan01** [comment]
I would love to

**Comment by SaptarshiSarkar12** [comment]
> I would love to

Ok assigning you @frypan01 .

**Comment by JakubPristas** [comment]
Can you assign me to this issue?

**Comment by SaptarshiSarkar12** [comment]
@frypan01 is already working on this issue and has already opened a PR (#106) that is currently under review. @JakubPristas You may modify that through another PR. Or, you may work on other parts of this project.

**Comment by Aditi-1709** [comment]
Can I work on this issue? I will also add the feature to move that navbar button according to the user's choice.

**Comment by SaptarshiSarkar12** [comment]
> Can I work on this issue? I will also add the feature to move that navbar button according to the user's choice.

Yes, you may @Aditi-1709.

**Comment by Arnab7456** [comment]
can update the navnar

**Comment by SaptarshiSarkar12** [comment]
> can update the navnar

@Arnab7456 Ok, you may do so. Please ensure that your changes should keep the nav bar responsive and visually appealing. Assigning you with the task.

**Comment by SaptarshiSarkar12** [comment]
Closing this issue as it has been inactive.
