### ISSUE TITLE
[FEATURE] can add social handles in the footer 

### ISSUE THREAD

**Issue by Shashwat0227** [SaptarshiSarkar12/Drifty#9]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SaptarshiSarkar12** [comment]
Thanks for this issue. I am assigning you with the task. **Please fill the issue template (atleast describe the feature in brief)**. Please ensure that you will link this issue to your PR .

**Comment by Shashwat0227** [comment]
on the site which is being made i can add all the social handles of yours with the tag of that social handle and it will look good only

**Comment by SaptarshiSarkar12** [comment]
@Anshuman047 , @Shashwat0227 is already assigned with the task. So, you may modify it if required afterwards. Or, you may open an issue for any new feature that you want to include or a bug that you have discovered.

**Comment by Shashwat0227** [comment]
hey i added the footers and social 
check it
