### ISSUE TITLE
[BUG] The Download Section has different font than other sections

### ISSUE THREAD

**Issue by SujalSamai** [SaptarshiSarkar12/Drifty#90]
### Describe the bug

While all the sections of the website are no using a consistent font-style, the heading section of Downloads is still using some old font, which make it look not consistent with the page style.

### Steps To Reproduce

1. Go to Home Page
2. Scroll to Downloads section
3. Check its Heading
4. See the error

### Expected Behavior

The Download Section's heading should be consistent with the page and should have similar styling to other sections of the page. This is how UI Designing works. So I would like to work on this issue

### Operating System

Windows

### Application Version

v1.1.0

### Screenshots

![image](https://user-images.githubusercontent.com/87236576/194738588-82a09cb3-aef8-4e51-98ba-78359f44e7fa.png)

**Comment by SaptarshiSarkar12** [comment]
Great @SujalSamai! Assigning you with the task. Please link this issue to your PR.

**Comment by manishgupta416** [comment]
Can you assign to me?

**Comment by SaptarshiSarkar12** [comment]
@SujalSamai is already assigned. So, after @SujalSamai 's PR is merged, @manishgupta416, you may open another PR to modify those changes.
