### ISSUE TITLE
[FEATURE] Better UI for the dark mode button

### ISSUE THREAD

**Issue by bhumika-1-3** [SaptarshiSarkar12/Drifty#91]
### Is your feature request related to a problem? Please describe.

Yes. When you click on the dark mode that button blends with the background.

### Describe the solution you'd like.

A sticky Floating button for the dark mode so people can shift modes any where in the page

### Application Version

v1.1.0

**Comment by SaptarshiSarkar12** [comment]
Great @bhumika-1-3 😄! Do you want to work on this issue?

**Comment by bhumika-1-3** [comment]
Yes Sure .

**Comment by SaptarshiSarkar12** [comment]
ok assigning @bhumika-1-3. Please link this issue to your PR.
